=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/camping-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/camping-activity.json",
  "title": "Camping Activity",
  "description": "A camping activity",
  "$ref": "#/$defs/CampingActivity",
  "$defs": {
    "CampingActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "isHomebrew",
        "isSecret",
        "isLocked",
        "skills"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "journalUuid": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CampingSkill"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        }
      }
    },
    "CampingSkill": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "dcType",
        "proficiency"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "proficiency": {
          "type": "string",
          "enum": [
            "untrained",
            "trained",
            "expert",
            "master",
            "legendary"
          ]
        },
        "dc": {
          "type": "number"
        },
        "validateOnly": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "dcType": {
          "type": "string",
          "enum": [
            "zone",
            "actorLevel",
            "none",
            "static"
          ]
        }
      }
    },
    "ModifyEncounterDc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "day",
        "night"
      ],
      "properties": {
        "day": {
          "type": "number"
        },
        "night": {
          "type": "number"
        }
      }
    },
    "ActivityEffect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "enum": [
            "all",
            "self",
            "allies"
          ]
        },
        "doublesHealing": {
          "type": "boolean"
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "checkRandomEncounter": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Healer's Blessing.json
{
  "name": "Healer's Blessing",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.X4ggcXUe0wPiW4jt",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.eaWmjDOIvUF9aDbq",
      "doublesHealing": true
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Enhance Campfire.json
{
  "name": "Enhance Campfire",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.ytyW9F39m7xf0gx5",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.NFPQHxvpJd2vsKMe"
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Wilderness Survival.json
{
  "name": "Wilderness Survival",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.8PNH77YHVkw9KoAv",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.v9i9W49PeJ9NkfXX"
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Set Alarms.json
{
  "name": "Set Alarms",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.vWSQmYLKlrk3rLDE",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.ptjs54eoEX8EAQNq"
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Bolster Confidence.json
{
  "name": "Bolster Confidence",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.pxHYFLK7VYGppCzS",
  "isLocked": true,
  "isSecret": false,
  "skills": [],
  "isHomebrew": false,
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.mAEvnTqFuLIASQLB"
    }
  ]
}
