=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/charter.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/charter.json",
  "title": "Kingdom Charter",
  "description": "A Kingdom Charter",
  "$ref": "#/$defs/Charter",
  "$defs": {
    "Charter": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "description",
        "freeBoosts",
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "freeBoosts": {
          "type": "number"
        },
        "flaw": {
          "$ref": "#/$defs/Ability"
        },
        "boost": {
          "$ref": "#/$defs/Ability"
        },
        "description": {
          "type": "string"
        }
      }
    },
    "Ability": {
      "type": "string",
      "enum": [
        "stability",
        "culture",
        "economy",
        "loyalty"
      ]
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/charters/Conquest.json
{
    "id": "conquest",
    "name": "Conquest",
    "description": "Your sponsors have conquered an area and its former leaders have been routed or even killed. This charter places you in charge of some portion of this conquered territory (or land abandoned by the defeated enemy) and commands you to hold and pacify it in the name of your patron. The people are particularly devoted and supportive of your rule (if partially out of fear), but the constant threat of potential war hinders the arts and makes it difficult for citizens to truly relax.",
    "boost": "loyalty",
    "freeBoosts": 1,
    "flaw": "culture"
}
