=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/event.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/event.json",
  "title": "Kingdom Event",
  "description": "A Kingdom Event",
  "$ref": "#/$defs/Event",
  "$defs": {
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "description",
        "id",
        "traits"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "globalModifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        },
        "automationNotes": {
          "type": "string"
        },
        "special": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        },
        "resolution": {
          "type": "string"
        },
        "resolvedOn": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DegreeOfSuccess"
          }
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "modifier": {
          "type": "number"
        },
        "traits": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EventTraits"
          }
        },
        "location": {
          "type": "string"
        },
        "stages": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EventStage"
          }
        }
      }
    },
    "EventStage": {
      "type": "object",
      "required": [
        "skills",
        "leader"
      ],
      "additionalProperties": false,
      "properties": {
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/KingdomSkill"
          }
        },
        "leader": {
          "$ref": "#/$defs/Leader"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/EventOutcome"
        },
        "success": {
          "$ref": "#/$defs/EventOutcome"
        },
        "failure": {
          "$ref": "#/$defs/EventOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/EventOutcome"
        }
      }
    },
    "EventOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "msg"
      ],
      "properties": {
        "msg": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        }
      }
    },
    "Modifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "value",
        "name",
        "enabled",
        "buttonLabel"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "proficiency",
            "item",
            "status",
            "circumstance",
            "vacancy",
            "untyped",
            "leadership"
          ]
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "note"
            ],
            "properties": {
              "note": {
                "type": "string"
              },
              "degree": {
                "$ref": "#/$defs/DegreeOfSuccess"
              }
            }
          }
        },
        "upgradeResults": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/UpgradeResult"
          }
        },
        "downgradeResults": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DowngradeResult"
          }
        },
        "fortune": {
          "type": "boolean"
        },
        "rollTwiceKeepHighest": {
          "type": "boolean"
        },
        "rollTwiceKeepLowest": {
          "type": "boolean"
        },
        "buttonLabel": {
          "type": "string"
        },
        "value": {
          "type": "number"
        },
        "valueExpression": {
          "$ref": "#/$defs/When"
        },
        "name": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "turns": {
          "type": "number"
        },
        "isConsumedAfterRoll": {
          "type": "boolean"
        },
        "rollOptions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "applyIf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "DowngradeResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "downgrade"
      ],
      "properties": {
        "downgrade": {
          "$ref": "#/$defs/DegreeOfSuccess"
        },
        "times": {
          "type": "number"
        },
        "predicate": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "UpgradeResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "upgrade"
      ],
      "properties": {
        "times": {
          "type": "number"
        },
        "upgrade": {
          "$ref": "#/$defs/DegreeOfSuccess"
        },
        "predicate": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "Predicate": {
      "oneOf": [
        {
          "$ref": "#/$defs/GtePredicate"
        },
        {
          "$ref": "#/$defs/GtPredicate"
        },
        {
          "$ref": "#/$defs/LtePredicate"
        },
        {
          "$ref": "#/$defs/LtPredicate"
        },
        {
          "$ref": "#/$defs/EqPredicate"
        },
        {
          "$ref": "#/$defs/SomePredicate"
        },
        {
          "$ref": "#/$defs/AllPredicate"
        },
        {
          "$ref": "#/$defs/NotPredicate"
        },
        {
          "$ref": "#/$defs/HasRollOptionPredicate"
        },
        {
          "$ref": "#/$defs/InPredicate"
        }
      ]
    },
    "InPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "in"
      ],
      "properties": {
        "in": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AnyScalar"
            },
            {
              "oneOf": [
                {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/AnyScalar"
                  }
                },
                {
                  "type": "string"
                }
              ]
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gte"
      ],
      "properties": {
        "gte": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "GtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gt"
      ],
      "properties": {
        "gt": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "LtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lte"
      ],
      "properties": {
        "lte": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "LtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lt"
      ],
      "properties": {
        "lt": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "EqPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "eq"
      ],
      "properties": {
        "eq": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AnyScalar"
            },
            {
              "$ref": "#/$defs/AnyScalar"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "SomePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "some"
      ],
      "properties": {
        "some": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          },
          "minItems": 1
        }
      }
    },
    "AllPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "all"
      ],
      "properties": {
        "all": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          },
          "minItems": 1
        }
      }
    },
    "NotPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "not"
      ],
      "properties": {
        "not": {
          "$ref": "#/$defs/Predicate"
        }
      }
    },
    "HasRollOptionPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasRollOption"
      ],
      "properties": {
        "hasRollOption": {
          "type": "string"
        }
      }
    },
    "When": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "when"
      ],
      "properties": {
        "when": {
          "type": "object",
          "required": [
            "cases"
          ],
          "additionalProperties": false,
          "properties": {
            "cases": {
              "type": "array",
              "minItems": 1,
              "items": {
                "$ref": "#/$defs/Case"
              }
            },
            "default": {
              "$ref": "#/$defs/AnyScalar"
            }
          }
        }
      }
    },
    "Case": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "case"
      ],
      "properties": {
        "case": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/Predicate"
            },
            {
              "$ref": "#/$defs/AnyScalar"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "AnyNumeric": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ]
    },
    "AnyScalar": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        }
      ]
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "DegreeOfSuccess": {
      "type": "string",
      "enum": [
        "criticalSuccess",
        "success",
        "failure",
        "criticalFailure"
      ]
    },
    "Leader": {
      "type": "string",
      "enum": [
        "ruler",
        "counselor",
        "emissary",
        "general",
        "magister",
        "treasurer",
        "viceroy",
        "warden"
      ]
    },
    "EventTraits": {
      "type": "string",
      "enum": [
        "continuous",
        "dangerous",
        "settlement",
        "beneficial",
        "hex",
        "fortune",
        "downtime",
        "leadership"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Remarkable Treasure.json
{
  "id": "remarkable-treasure",
  "name": "events.remarkable-treasure.name",
  "traits": [
    "beneficial",
    "fortune"
  ],
  "modifier": 2,
  "description": "events.remarkable-treasure.description",
  "stages": [
    {
      "leader": "emissary",
      "skills": [
        "exploration"
      ],
      "criticalSuccess": {
        "msg": "events.remarkable-treasure.stage-0.criticalSuccess.msg",
        "modifiers": [
          {
            "name": "Remarkable Treasure: Critical Success",
            "buttonLabel": "Roll Twice and Take Better Result if Hiring Adventurers",
            "turns": 2,
            "rollTwiceKeepHighest": true,
            "type": "untyped",
            "enabled": true,
            "value": 0,
            "applyIf": [
              {
                "eq": [
                  "@action",
                  "hire-adventurers"
                ]
              }
            ]
          }
        ]
      },
      "success": {
        "msg": "events.remarkable-treasure.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.remarkable-treasure.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.remarkable-treasure.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Troll Sightings.json
{
  "id": "troll-sightings",
  "name": "events.troll-sightings.name",
  "traits": [
    "continuous",
    "dangerous"
  ],
  "description": "events.troll-sightings.description",
  "stages": [
    {
      "leader": "warden",
      "skills": [
        "defense"
      ],
      "criticalSuccess": {
        "msg": "events.troll-sightings.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.troll-sightings.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.troll-sightings.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.troll-sightings.stage-0.criticalFailure.msg"
      }
    }
  ],
  "resolution": "events.troll-sightings.resolution"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Monster Activity.json
{
  "id": "monster-activity",
  "name": "events.monster-activity.name",
  "traits": [
    "dangerous",
    "continuous",
    "hex"
  ],
  "location": "events.monster-activity.location",
  "description": "events.monster-activity.description",
  "stages": [
    {
      "leader": "ruler",
      "skills": [
        "defense"
      ],
      "criticalSuccess": {
        "msg": "events.monster-activity.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.monster-activity.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.monster-activity.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.monster-activity.stage-0.criticalFailure.msg"
      }
    }
  ],
  "resolvedOn": [
    "criticalSuccess"
  ],
  "resolution": "events.monster-activity.resolution"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/The Founding of a Village.json
{
  "id": "the-founding-of-a-village",
  "name": "events.the-founding-of-a-village.name",
  "traits": [
    "beneficial",
    "hex"
  ],
  "location": "events.the-founding-of-a-village.location",
  "description": "events.the-founding-of-a-village.description",
  "stages": [
    {
      "skills": [
        "exploration"
      ],
      "leader": "warden",
      "criticalSuccess": {
        "msg": "events.the-founding-of-a-village.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.the-founding-of-a-village.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.the-founding-of-a-village.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.the-founding-of-a-village.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Drug Den.json
{
  "id": "drug-den",
  "name": "events.drug-den.name",
  "traits": [
    "continuous",
    "dangerous",
    "settlement"
  ],
  "modifier": 1,
  "location": "events.drug-den.location",
  "description": "events.drug-den.description",
  "stages": [
    {
      "leader": "counselor",
      "skills": [
        "intrigue"
      ],
      "criticalSuccess": {
        "msg": "events.drug-den.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.drug-den.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.drug-den.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.drug-den.stage-0.criticalFailure.msg"
      }
    }
  ],
  "resolvedOn": [
    "criticalSuccess"
  ],
  "resolution": "events.drug-den.resolution"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Discover Desperate Spies.json
{
  "id": "discover-desperate-spies",
  "name": "Discover Desperate Spies",
  "modifier": 3,
  "location": "The kingdomâ€™s capital city",
  "traits": [
    "continuous",
    "dangerous",
    "settlement"
  ],
  "description": "The kobold spies slink and skulk around the city, looking for weaknesses to report back to the troll king and taking advantage of opportunities to perform minor acts of vandalism and sabotage. Once this story event begins, it continues daily for a week. Each day, the kingdom attempts a skill check to resolve the event. The Intrigue check gains the Secret trait.",
  "stages": [
    {
      "skills": ["intrigue", "defense"],
      "leader": "warden",
      "criticalSuccess": {
        "msg": "The two kobold spies are captured and kept imprisoned until the PCs have a chance to speak to them."
      },
      "success": {
        "msg": "Rumors of kobold spies in town begin to spread. Attempt a @Check[type:flat|dc:11]; on a failure, @gain1Unrest."
      },
      "failure": {
        "msg": "Someone or something in town is causing trouble. @gain1Unrest"
      },
      "criticalFailure": {
        "msg": "Not only do the kobolds continue to cause trouble @gain1Unrest, but they also perform acts of vandalism and sabotage. @gain1Decay"
      }
    }
  ],
  "resolvedOn": ["criticalSuccess"],
  "resolution": "This daily event ends on a Critical Success or after 7 days have passed."
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Public Scandal.json
{
  "id": "public-scandal",
  "name": "events.public-scandal.name",
  "traits": [
    "dangerous"
  ],
  "description": "events.public-scandal.description",
  "stages": [
    {
      "leader": "counselor",
      "skills": [
        "intrigue"
      ],
      "criticalSuccess": {
        "msg": "events.public-scandal.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.public-scandal.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.public-scandal.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.public-scandal.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Plague.json
{
  "id": "plague",
  "name": "events.plague.name",
  "modifier": 1,
  "traits": [
    "continuous",
    "dangerous",
    "settlement"
  ],
  "location": "events.plague.location",
  "description": "events.plague.description",
  "modifiers": [
    {
      "type": "item",
      "name": "No Dump in Settlement",
      "buttonLabel": "No Dump in Settlement",
      "value": -4,
      "enabled": true,
      "applyIf": [
        {
          "not": {
            "in": [
              "dump",
              "@structures"
            ]
          }
        }
      ]
    },
    {
      "type": "item",
      "name": "Has Sewer System in Settlement",
      "buttonLabel": "Has Sewer System in Settlement",
      "value": 2,
      "enabled": true,
      "applyIf": [
        {
          "in": [
            "sewer-system",
            "@structures"
          ]
        }
      ]
    }
  ],
  "stages": [
    {
      "leader": "ruler",
      "skills": [
        "defense"
      ],
      "criticalSuccess": {
        "msg": "events.plague.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.plague.stage-0.success.msg",
        "modifiers": [
          {
            "type": "status",
            "name": "Settlement without Sewer System suffering from Plague",
            "buttonLabel": "Plague Civic penalty",
            "value": -2,
            "enabled": true,
            "applyIf": [
              {
                "eq": [
                  "@phase",
                  "civic"
                ]
              },
              {
                "in": [
                  "plague",
                  "@settlementEvents"
                ]
              },
              {
                "not": {
                  "in": [
                    "sewer-system",
                    "@structures"
                  ]
                }
              }
            ]
          }
        ]
      },
      "failure": {
        "msg": "events.plague.stage-0.failure.msg",
        "modifiers": [
          {
            "type": "status",
            "name": "Settlement without Sewer System suffering from Plague",
            "buttonLabel": "Plague Civic penalty",
            "value": -2,
            "enabled": true,
            "applyIf": [
              {
                "eq": [
                  "@phase",
                  "civic"
                ]
              },
              {
                "in": [
                  "plague",
                  "@settlementEvents"
                ]
              },
              {
                "not": {
                  "in": [
                    "sewer-system",
                    "@structures"
                  ]
                }
              }
            ]
          }
        ]
      },
      "criticalFailure": {
        "msg": "events.plague.stage-0.criticalFailure.msg",
        "modifiers": [
          {
            "type": "status",
            "name": "Settlement without Sewer System suffering from Plague",
            "buttonLabel": "Plague Civic penalty",
            "value": -2,
            "enabled": true,
            "applyIf": [
              {
                "eq": [
                  "@phase",
                  "civic"
                ]
              },
              {
                "in": [
                  "plague",
                  "@settlementEvents"
                ]
              },
              {
                "not": {
                  "in": [
                    "sewer-system",
                    "@structures"
                  ]
                }
              }
            ]
          }
        ]
      }
    }
  ],
  "resolvedOn": [
    "criticalSuccess"
  ],
  "resolution": "events.plague.resolution",
  "special": "events.plague.special"
}
