=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/event.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/event.json",
  "title": "Kingdom Event",
  "description": "A Kingdom Event",
  "$ref": "#/$defs/Event",
  "$defs": {
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "description",
        "id",
        "traits"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "globalModifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        },
        "automationNotes": {
          "type": "string"
        },
        "special": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        },
        "resolution": {
          "type": "string"
        },
        "resolvedOn": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DegreeOfSuccess"
          }
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "modifier": {
          "type": "number"
        },
        "traits": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EventTraits"
          }
        },
        "location": {
          "type": "string"
        },
        "stages": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EventStage"
          }
        }
      }
    },
    "EventStage": {
      "type": "object",
      "required": [
        "skills",
        "leader"
      ],
      "additionalProperties": false,
      "properties": {
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/KingdomSkill"
          }
        },
        "leader": {
          "$ref": "#/$defs/Leader"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/EventOutcome"
        },
        "success": {
          "$ref": "#/$defs/EventOutcome"
        },
        "failure": {
          "$ref": "#/$defs/EventOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/EventOutcome"
        }
      }
    },
    "EventOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "msg"
      ],
      "properties": {
        "msg": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        }
      }
    },
    "Modifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "value",
        "name",
        "enabled",
        "buttonLabel"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "proficiency",
            "item",
            "status",
            "circumstance",
            "vacancy",
            "untyped",
            "leadership"
          ]
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "note"
            ],
            "properties": {
              "note": {
                "type": "string"
              },
              "degree": {
                "$ref": "#/$defs/DegreeOfSuccess"
              }
            }
          }
        },
        "upgradeResults": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/UpgradeResult"
          }
        },
        "downgradeResults": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DowngradeResult"
          }
        },
        "fortune": {
          "type": "boolean"
        },
        "rollTwiceKeepHighest": {
          "type": "boolean"
        },
        "rollTwiceKeepLowest": {
          "type": "boolean"
        },
        "buttonLabel": {
          "type": "string"
        },
        "value": {
          "type": "number"
        },
        "valueExpression": {
          "$ref": "#/$defs/When"
        },
        "name": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "turns": {
          "type": "number"
        },
        "isConsumedAfterRoll": {
          "type": "boolean"
        },
        "rollOptions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "applyIf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "DowngradeResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "downgrade"
      ],
      "properties": {
        "downgrade": {
          "$ref": "#/$defs/DegreeOfSuccess"
        },
        "times": {
          "type": "number"
        },
        "predicate": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "UpgradeResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "upgrade"
      ],
      "properties": {
        "times": {
          "type": "number"
        },
        "upgrade": {
          "$ref": "#/$defs/DegreeOfSuccess"
        },
        "predicate": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "Predicate": {
      "oneOf": [
        {
          "$ref": "#/$defs/GtePredicate"
        },
        {
          "$ref": "#/$defs/GtPredicate"
        },
        {
          "$ref": "#/$defs/LtePredicate"
        },
        {
          "$ref": "#/$defs/LtPredicate"
        },
        {
          "$ref": "#/$defs/EqPredicate"
        },
        {
          "$ref": "#/$defs/SomePredicate"
        },
        {
          "$ref": "#/$defs/AllPredicate"
        },
        {
          "$ref": "#/$defs/NotPredicate"
        },
        {
          "$ref": "#/$defs/HasRollOptionPredicate"
        },
        {
          "$ref": "#/$defs/InPredicate"
        }
      ]
    },
    "InPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "in"
      ],
      "properties": {
        "in": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AnyScalar"
            },
            {
              "oneOf": [
                {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/AnyScalar"
                  }
                },
                {
                  "type": "string"
                }
              ]
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gte"
      ],
      "properties": {
        "gte": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "GtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gt"
      ],
      "properties": {
        "gt": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "LtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lte"
      ],
      "properties": {
        "lte": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "LtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lt"
      ],
      "properties": {
        "lt": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "EqPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "eq"
      ],
      "properties": {
        "eq": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AnyScalar"
            },
            {
              "$ref": "#/$defs/AnyScalar"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "SomePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "some"
      ],
      "properties": {
        "some": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          },
          "minItems": 1
        }
      }
    },
    "AllPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "all"
      ],
      "properties": {
        "all": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          },
          "minItems": 1
        }
      }
    },
    "NotPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "not"
      ],
      "properties": {
        "not": {
          "$ref": "#/$defs/Predicate"
        }
      }
    },
    "HasRollOptionPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasRollOption"
      ],
      "properties": {
        "hasRollOption": {
          "type": "string"
        }
      }
    },
    "When": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "when"
      ],
      "properties": {
        "when": {
          "type": "object",
          "required": [
            "cases"
          ],
          "additionalProperties": false,
          "properties": {
            "cases": {
              "type": "array",
              "minItems": 1,
              "items": {
                "$ref": "#/$defs/Case"
              }
            },
            "default": {
              "$ref": "#/$defs/AnyScalar"
            }
          }
        }
      }
    },
    "Case": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "case"
      ],
      "properties": {
        "case": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/Predicate"
            },
            {
              "$ref": "#/$defs/AnyScalar"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "AnyNumeric": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ]
    },
    "AnyScalar": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        }
      ]
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "DegreeOfSuccess": {
      "type": "string",
      "enum": [
        "criticalSuccess",
        "success",
        "failure",
        "criticalFailure"
      ]
    },
    "Leader": {
      "type": "string",
      "enum": [
        "ruler",
        "counselor",
        "emissary",
        "general",
        "magister",
        "treasurer",
        "viceroy",
        "warden"
      ]
    },
    "EventTraits": {
      "type": "string",
      "enum": [
        "continuous",
        "dangerous",
        "settlement",
        "beneficial",
        "hex",
        "fortune",
        "downtime",
        "leadership"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Public Outburst.json
{
  "id": "public-outburst",
  "name": "events.public-outburst.name",
  "traits": [
    "dangerous"
  ],
  "description": "events.public-outburst.description",
  "modifiers": [
    {
      "type": "untyped",
      "value": -1,
      "name": "Event Occurred Once",
      "buttonLabel": "Event Occurred Once",
      "enabled": false
    },
    {
      "type": "untyped",
      "value": -2,
      "name": "Event Occurred More Than Once",
      "buttonLabel": "Event Occurred More Than Once",
      "enabled": false
    }
  ],
  "stages": [
    {
      "leader": "ruler",
      "skills": [
        "politics"
      ],
      "criticalSuccess": {
        "msg": "events.public-outburst.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.public-outburst.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.public-outburst.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.public-outburst.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Discovery.json
{
  "id": "discovery",
  "name": "Discovery",
  "traits": ["beneficial"],
  "description": "Scholars unearth a bit of ancient lore or devise important new research of their own.",
  "stages": [
    {
      "leader": "counselor",
      "skills": ["scholarship"],
      "criticalSuccess": {
        "msg": "Your discovery brings glory and a boon to your resources! <button type=\"button\" class=\"km-gain-lose\" data-type=\"fame\" data-mode=\"gain\" data-turn=\"next\" data-multiple=\"false\" data-value=\"1\">Gain 1 Fame Next Turn</button> and <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-dice\" data-mode=\"gain\" data-turn=\"next\" data-multiple=\"false\" data-value=\"6\">Gain 6 Resource Dice Next Turn</button>. Your people are amazed. @lose2Unrest"
      },
      "success": {
        "msg": "Your discovery is a helpful (but not overly amazing) boon to your kingdomâ€™s resources. <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-dice\" data-mode=\"gain\" data-turn=\"next\" data-multiple=\"false\" data-value=\"3\">Gain 3 Resource Dice Next Turn</button>"
      },
      "failure": {
        "msg": "Your discovery is of some academic interest but ultimately of limited use. @gain1ResourceDiceNextTurn"
      },
      "criticalFailure": {
        "msg": "Your discovery turns out to be a dead end and a wasteful boondoggle. @lose2ResourceDiceNextTurn"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/A Devil Comes Calling.json
{
  "id": "a-devil-comes-calling",
  "name": "A Devil Comes Calling",
  "location": "The closest settlement to the kobold caverns",
  "description": "The devil comes looking for the its worshippers, finds them allied with the PCs, and works from behind the scenes in a nearby settlement to wreak havoc and bolster the cult he didn’t know he had, spreading his influence through the kingdom.",
  "modifier": 3,
  "traits": ["continuous", "dangerous", "settlement"],
  "stages": [
    {
      "leader": "warden",
      "skills": ["intrigue"],
      "criticalSuccess": {
        "msg": "Kingdom agents manage to isolate the source of the diabolic influence: the devil has made a hidden lair within the settlement; the PCs have discovered where this secret den is located, and can finally take direct action to resolve the event."
      },
      "success": {
        "msg": "The devil's influence spreads, but the speed of its growth is stemmed by the investigations. <button type=\"button\" class=\"km-gain-lose\" data-type=\"unrest\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Unrest</button> and increase a Ruin of your choice by 1 <ul><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"crime\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Crime</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"corruption\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Corruption</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"decay\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Decay</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"strife\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Strife</button></li></ul>"
      },
      "failure": {
        "msg": "The devil's cult gains ground as he begins to destroy the kingdom from within. <button type=\"button\" class=\"km-gain-lose\" data-type=\"unrest\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1d4\">Gain 1d4 Unrest</button> and increase three Ruins of your choice by 1 <ul><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"crime\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Crime</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"corruption\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Corruption</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"decay\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Decay</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"strife\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Strife</button></li></ul>"
      },
      "criticalFailure": {
        "msg": "The devil's cult gains ground as he begins to destroy the kingdom from within. <button type=\"button\" class=\"km-gain-lose\" data-type=\"unrest\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1d4\">Gain 1d4 Unrest</button> and increase three Ruins of your choice by 1 <ul><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"crime\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Crime</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"corruption\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Corruption</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"decay\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Decay</button></li><li><button type=\"button\" class=\"km-gain-lose\" data-type=\"strife\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Strife</button></li></ul>In addition, the devil corrupts an NPC leader, convincing them to join his cult and abandon their responsibilities to the kingdom. Treat that leadership role as vacant until this event is resolved or the NPC leader is replaced or redeemed."
      }
    }
  ],
  "resolvedOn": ["criticalSuccess"],
  "resolution": "Once the PCs get a critical success (or at your discretion, after the PCs undertake an adventure of your own design to discover his lair), they can drive the devil out of their kingdom by attacking and defeating him (in which case you’ll need to play the battle out in a location of your choice), or they can attempt a Hire Adventurers activity to do the same. If, by the Event phase of the next Kingdom turn, he hasn’t been defeated, he moves to a new settlement and the event continues."
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/The Rampage of the Owlbear.json
{
  "id": "the-rampage-of-the-owlbear",
  "name": "events.the-rampage-of-the-owlbear.name",
  "modifier": 4,
  "traits": [
    "dangerous",
    "settlement"
  ],
  "location": "events.the-rampage-of-the-owlbear.location",
  "description": "events.the-rampage-of-the-owlbear.description",
  "modifiers": [
    {
      "name": "Settlement has only Water Borders",
      "buttonLabel": "Settlement has only Water Borders",
      "value": 0,
      "enabled": true,
      "applyIf": [
        {
          "eq": [
            "@waterBorders",
            4
          ]
        }
      ],
      "type": "untyped",
      "upgradeResults": [
        {
          "upgrade": "criticalFailure"
        },
        {
          "upgrade": "failure"
        },
        {
          "upgrade": "success"
        }
      ]
    }
  ],
  "stages": [
    {
      "leader": "warden",
      "skills": [
        "defense"
      ],
      "criticalSuccess": {
        "msg": "events.the-rampage-of-the-owlbear.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.the-rampage-of-the-owlbear.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.the-rampage-of-the-owlbear.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.the-rampage-of-the-owlbear.stage-0.criticalFailure.msg"
      }
    }
  ],
  "resolution": "events.the-rampage-of-the-owlbear.resolution"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Feud.json
{
  "id": "feud",
  "name": "events.feud.name",
  "traits": [
    "continuous",
    "dangerous",
    "settlement"
  ],
  "description": "events.feud.description",
  "location": "events.feud.location",
  "stages": [
    {
      "leader": "counselor",
      "skills": [
        "politics"
      ],
      "criticalSuccess": {
        "msg": "events.feud.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.feud.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.feud.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.feud.stage-0.criticalFailure.msg"
      }
    }
  ],
  "resolvedOn": [
    "criticalSuccess"
  ],
  "resolution": "events.feud.resolution"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Trouble with a Weird Gnome.json
{
  "id": "trouble-with-a-weird-gnome",
  "name": "events.trouble-with-a-weird-gnome.name",
  "traits": [
    "dangerous"
  ],
  "description": "events.trouble-with-a-weird-gnome.description",
  "stages": [
    {
      "leader": "magister",
      "skills": [
        "intrigue"
      ],
      "criticalSuccess": {
        "msg": "events.trouble-with-a-weird-gnome.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.trouble-with-a-weird-gnome.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.trouble-with-a-weird-gnome.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.trouble-with-a-weird-gnome.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Squatters.json
{
  "id": "squatters",
  "name": "Squatters",
  "modifier": -1,
  "traits": [
    "continuous",
    "dangerous",
    "settlement"
  ],
  "location": "The settlement with the highest Consumption in the kingdom or the largest settlement in the kingdom (as chosen by the GM)",
  "description": "An empty lot in your settlement is taken over by desperate people unable to find adequate work or housing. They set up camp with tents, wagons, and shanties. You cannot use the lot for anything until the squatters are given places to live.",
  "automationNotes": "Consumption increase per settlement on a Critical Failure is not implemented",
  "stages": [
    {
      "leader": "viceroy",
      "skills": [
        "politics"
      ],
      "criticalSuccess": {
        "msg": "You find opportunities for the squatters to improve their lot in life."
      },
      "success": {
        "msg": "The squatters are removed from their lot, and they try to relocate and reintegrate with other citizens, but there is some strife. @gain1Unrest"
      },
      "failure": {
        "msg": "The squatters refuse to leave their lot and other citizens are split, with some decrying their mistreatment while others call for harsh measures to drive them out. @gain1d4Unrest"
      },
      "criticalFailure": {
        "msg": "The squatters refuse to leave their lot and other citizens are split, with some decrying their mistreatment while others call for harsh measures to drive them out. @gain1d4Unrest. In addition, on your next Kingdom turn attempt a @Check[type:flat|dc:6]; on failure, the squatters spread to the nearest empty lot in the settlement, creating a separate continuous Squatters event starting with your next Kingdom turn. In addition, the squatters increase the settlementâ€™s Consumption by 1 each month until the event is resolved. @gain1ConsumptionNextTurn"
      }
    }
  ],
  "modifiers": [
    {
      "name": "Sewer System in Settlement",
      "buttonLabel": "Sewer System in Settlement",
      "value": 2,
      "type": "item",
      "enabled": true,
      "applyIf": [
        {
          "in": [
            "sewer-system",
            "@structures"
          ]
        }
      ]
    }
  ],
  "special": "If the settlement has a Sewer System, most of the squatters opt to live there instead; gain a +2 item bonus to checks to resolve this event.",
  "resolution": "This continuous event ends when you achieve a critical success on the check or when you build a Residential structure in the lot the Squatters have chosen to live in.",
  "resolvedOn": [
    "criticalSuccess"
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/New Subjects.json
{
  "id": "new-subjects",
  "name": "New Subjects",
  "traits": ["beneficial"],
  "description": "A small group of intelligent creatures joins your kingdom and submits to your rule, bringing along their knowledge of hidden places within your kingdom. (The exact nature and ancestry of these new subjects is determined by the GM.)",
  "stages": [
    {
      "leader": "emissary",
      "skills": ["statecraft"],
      "criticalSuccess": {
        "msg": "Your subjects blend in seamlessly and are welcomed by your citizens, while bringing their own unique contributions to your kingdom. You @gain6ResourceDiceNextTurn, and you gain an additional Region activity during the Activity phase of the next Kingdom turn."
      },
      "success": {
        "msg": "Your new subjects are welcomed, and their contributions help in the short term. @gain3ResourceDiceNextTurn"
      },
      "failure": {
        "msg": "Your new subjects endure discrimination from intolerant citizens in your kingdom, but they nonetheless bring willing hands to work and such resources as they possess. @gain1Unrest and @gain1ResourceDiceNextTurn"
      },
      "criticalFailure": {
        "msg": "Your new subjects encounter discrimination and xenophobia, and they are eventually driven back into the wild. @gain1d4Unrest and @gain1Strife"
      }
    }
  ]
}
