=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/event.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/event.json",
  "title": "Kingdom Event",
  "description": "A Kingdom Event",
  "$ref": "#/$defs/Event",
  "$defs": {
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "description",
        "id",
        "traits"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "globalModifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        },
        "automationNotes": {
          "type": "string"
        },
        "special": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        },
        "resolution": {
          "type": "string"
        },
        "resolvedOn": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DegreeOfSuccess"
          }
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "modifier": {
          "type": "number"
        },
        "traits": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EventTraits"
          }
        },
        "location": {
          "type": "string"
        },
        "stages": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EventStage"
          }
        }
      }
    },
    "EventStage": {
      "type": "object",
      "required": [
        "skills",
        "leader"
      ],
      "additionalProperties": false,
      "properties": {
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/KingdomSkill"
          }
        },
        "leader": {
          "$ref": "#/$defs/Leader"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/EventOutcome"
        },
        "success": {
          "$ref": "#/$defs/EventOutcome"
        },
        "failure": {
          "$ref": "#/$defs/EventOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/EventOutcome"
        }
      }
    },
    "EventOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "msg"
      ],
      "properties": {
        "msg": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        }
      }
    },
    "Modifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "value",
        "name",
        "enabled",
        "buttonLabel"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "proficiency",
            "item",
            "status",
            "circumstance",
            "vacancy",
            "untyped",
            "leadership"
          ]
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "note"
            ],
            "properties": {
              "note": {
                "type": "string"
              },
              "degree": {
                "$ref": "#/$defs/DegreeOfSuccess"
              }
            }
          }
        },
        "upgradeResults": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/UpgradeResult"
          }
        },
        "downgradeResults": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DowngradeResult"
          }
        },
        "fortune": {
          "type": "boolean"
        },
        "rollTwiceKeepHighest": {
          "type": "boolean"
        },
        "rollTwiceKeepLowest": {
          "type": "boolean"
        },
        "buttonLabel": {
          "type": "string"
        },
        "value": {
          "type": "number"
        },
        "valueExpression": {
          "$ref": "#/$defs/When"
        },
        "name": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "turns": {
          "type": "number"
        },
        "isConsumedAfterRoll": {
          "type": "boolean"
        },
        "rollOptions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "applyIf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "DowngradeResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "downgrade"
      ],
      "properties": {
        "downgrade": {
          "$ref": "#/$defs/DegreeOfSuccess"
        },
        "times": {
          "type": "number"
        },
        "predicate": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "UpgradeResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "upgrade"
      ],
      "properties": {
        "times": {
          "type": "number"
        },
        "upgrade": {
          "$ref": "#/$defs/DegreeOfSuccess"
        },
        "predicate": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "Predicate": {
      "oneOf": [
        {
          "$ref": "#/$defs/GtePredicate"
        },
        {
          "$ref": "#/$defs/GtPredicate"
        },
        {
          "$ref": "#/$defs/LtePredicate"
        },
        {
          "$ref": "#/$defs/LtPredicate"
        },
        {
          "$ref": "#/$defs/EqPredicate"
        },
        {
          "$ref": "#/$defs/SomePredicate"
        },
        {
          "$ref": "#/$defs/AllPredicate"
        },
        {
          "$ref": "#/$defs/NotPredicate"
        },
        {
          "$ref": "#/$defs/HasRollOptionPredicate"
        },
        {
          "$ref": "#/$defs/InPredicate"
        }
      ]
    },
    "InPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "in"
      ],
      "properties": {
        "in": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AnyScalar"
            },
            {
              "oneOf": [
                {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/AnyScalar"
                  }
                },
                {
                  "type": "string"
                }
              ]
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gte"
      ],
      "properties": {
        "gte": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "GtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gt"
      ],
      "properties": {
        "gt": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "LtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lte"
      ],
      "properties": {
        "lte": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "LtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lt"
      ],
      "properties": {
        "lt": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AnyNumeric"
          },
          "minItems": 2,
          "maxItems": 2
        }
      }
    },
    "EqPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "eq"
      ],
      "properties": {
        "eq": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AnyScalar"
            },
            {
              "$ref": "#/$defs/AnyScalar"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "SomePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "some"
      ],
      "properties": {
        "some": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          },
          "minItems": 1
        }
      }
    },
    "AllPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "all"
      ],
      "properties": {
        "all": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          },
          "minItems": 1
        }
      }
    },
    "NotPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "not"
      ],
      "properties": {
        "not": {
          "$ref": "#/$defs/Predicate"
        }
      }
    },
    "HasRollOptionPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasRollOption"
      ],
      "properties": {
        "hasRollOption": {
          "type": "string"
        }
      }
    },
    "When": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "when"
      ],
      "properties": {
        "when": {
          "type": "object",
          "required": [
            "cases"
          ],
          "additionalProperties": false,
          "properties": {
            "cases": {
              "type": "array",
              "minItems": 1,
              "items": {
                "$ref": "#/$defs/Case"
              }
            },
            "default": {
              "$ref": "#/$defs/AnyScalar"
            }
          }
        }
      }
    },
    "Case": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "case"
      ],
      "properties": {
        "case": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/Predicate"
            },
            {
              "$ref": "#/$defs/AnyScalar"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "AnyNumeric": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        }
      ]
    },
    "AnyScalar": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        }
      ]
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "DegreeOfSuccess": {
      "type": "string",
      "enum": [
        "criticalSuccess",
        "success",
        "failure",
        "criticalFailure"
      ]
    },
    "Leader": {
      "type": "string",
      "enum": [
        "ruler",
        "counselor",
        "emissary",
        "general",
        "magister",
        "treasurer",
        "viceroy",
        "warden"
      ]
    },
    "EventTraits": {
      "type": "string",
      "enum": [
        "continuous",
        "dangerous",
        "settlement",
        "beneficial",
        "hex",
        "fortune",
        "downtime",
        "leadership"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Barbarian Immigrants.json
{
  "id": "barbarian-immigrants",
  "name": "events.barbarian-immigrants.name",
  "description": "events.barbarian-immigrants.description",
  "modifier": 2,
  "traits": [
    "beneficial"
  ],
  "stages": [
    {
      "leader": "warden",
      "skills": [
        "statecraft"
      ],
      "criticalSuccess": {
        "msg": "events.barbarian-immigrants.stage-0.criticalSuccess.msg",
        "modifiers": [
          {
            "name": "events.barbarian-immigrants.stage-0.criticalSuccess.modifiers.barbarianSupport.name",
            "buttonLabel": "events.barbarian-immigrants.stage-0.criticalSuccess.modifiers.barbarianSupport.buttonLabel",
            "type": "circumstance",
            "value": 2,
            "enabled": true,
            "applyIf": [
              {
                "in": [
                  "@event",
                  [
                    "bandit-activity",
                    "monster-activity",
                    "undead-uprising"
                  ]
                ]
              }
            ]
          }
        ]
      },
      "success": {
        "msg": "events.barbarian-immigrants.stage-0.success.msg",
        "modifiers": [
          {
            "name": "events.barbarian-immigrants.stage-0.criticalSuccess.modifiers.barbarianSupport.name",
            "buttonLabel": "events.barbarian-immigrants.stage-0.criticalSuccess.modifiers.barbarianSupport.buttonLabel",
            "type": "circumstance",
            "value": 1,
            "enabled": true,
            "applyIf": [
              {
                "in": [
                  "@event",
                  [
                    "bandit-activity",
                    "monster-activity",
                    "undead-uprising"
                  ]
                ]
              }
            ]
          }
        ]
      },
      "failure": {
        "msg": "events.barbarian-immigrants.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.barbarian-immigrants.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Archeological Find.json
{
  "id": "archeological-find",
  "name": "events.archeological-find.name",
  "traits": [
    "beneficial",
    "hex"
  ],
  "location": "events.archeological-find.location",
  "description": "events.archeological-find.description",
  "stages": [
    {
      "leader": "viceroy",
      "skills": [
        "exploration"
      ],
      "criticalSuccess": {
        "msg": "events.archeological-find.stage-0.criticalSuccess.msg",
        "modifiers": [
          {
            "name": "Archeological Find",
            "buttonLabel": "+2 circumstance to Culture and Economy",
            "turns": 2,
            "enabled": true,
            "type": "circumstance",
            "value": 2,
            "applyIf": [
              {
                "some": [
                  {
                    "eq": [
                      "@ability",
                      "culture"
                    ]
                  },
                  {
                    "eq": [
                      "@ability",
                      "economy"
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      "success": {
        "msg": "events.archeological-find.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.archeological-find.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.archeological-find.stage-0.criticalFailure.msg",
        "modifiers": [
          {
            "name": "Reattempt Archeological Find",
            "buttonLabel": "Reattempt Archeological Find",
            "enabled": true,
            "type": "untyped",
            "value": -2
          }
        ]
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Natures Blessing.json
{
  "id": "natures-blessing",
  "name": "events.natures-blessing.name",
  "traits": [
    "beneficial"
  ],
  "description": "events.natures-blessing.description",
  "stages": [
    {
      "leader": "magister",
      "skills": [
        "arts"
      ],
      "criticalSuccess": {
        "msg": "events.natures-blessing.stage-0.criticalSuccess.msg",
        "modifiers": [
          {
            "type": "untyped",
            "name": "events.natures-blessing.stage-0.criticalSuccess.modifiers.glow.name",
            "buttonLabel": "events.natures-blessing.stage-0.criticalSuccess.modifiers.glow.buttonLabel",
            "value": 0,
            "turns": 2,
            "enabled": true,
            "applyIf": [
              {
                "in": [
                  "@activity",
                  [
                    "create-a-masterpiece",
                    "craft-luxuries"
                  ]
                ]
              }
            ],
            "upgradeResults": [
              {
                "upgrade": "success"
              },
              {
                "upgrade": "failure"
              },
              {
                "upgrade": "criticalFailure"
              }
            ]
          }
        ]
      },
      "success": {
        "msg": "events.natures-blessing.stage-0.success.msg",
        "modifiers": [
          {
            "name": "events.natures-blessing.stage-0.success.modifiers.glow.name",
            "buttonLabel": "events.natures-blessing.stage-0.success.modifiers.glow.buttonLabel",
            "enabled": true,
            "value": 1,
            "turns": 2,
            "type": "status",
            "applyIf": [
              {
                "in": [
                  "@ability",
                  [
                    "culture",
                    "stability"
                  ]
                ]
              }
            ]
          }
        ]
      },
      "failure": {
        "msg": "events.natures-blessing.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.natures-blessing.stage-0.criticalFailure.msg"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/Urban Outburst.json
{
  "id": "urban-outburst",
  "name": "Urban Outburst",
  "traits": ["dangerous", "settlement"],
  "modifier": 2,
  "location": "The settlement the PCs are currently located in, or the closest settlement to the PCs’ location if they’re not in a settlement.",
  "description": "A monster blooms from a citizen in the city itself and runs rampage through the streets! The type of monster should be chosen by the GM; its level should equal the party’s level + 2 (a Moderate threat encounter). The PCs can choose to resolve this event with a Kingdom skill check, or they can travel to the settlement the monster is rampaging in to challenge it in encounter mode. If they don’t defeat the monster by the end of the next day, treat this event as having a Critical Failure result.",
  "stages": [
    {
      "leader": "warden",
      "skills": ["defense"],
      "criticalSuccess": {
        "msg": "The monster is defeated before any more lives are lost"
      },
      "success": {
        "msg": "The monster is defeated but slew a citizen. @gain1Unrest"
      },
      "failure": {
        "msg": "The monster slays several citizens before it is defeated. @gain1d4Unrest and @gain1Decay"
      },
      "criticalFailure": {
        "msg": "The monster continues to rampage unopposed. This event becomes Continuous and occurs every day until the monster is defeated; additional Cult events still occur as normal. <button type=\"button\" class=\"km-gain-lose\" data-type=\"unrest\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1d6\">Gain 1d6 Unrest</button> and <button type=\"button\" class=\"km-gain-lose\" data-type=\"decay\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"2\">Gain 2 Decay</button>"
      }
    }
  ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/events/The Trial.json
{
  "id": "the-trial",
  "name": "events.the-trial.name",
  "traits": [
    "continuous",
    "downtime",
    "leadership"
  ],
  "description": "events.the-trial.description",
  "stages": [
    {
      "skills": [
        "intrigue",
        "politics",
        "statecraft"
      ],
      "leader": "emissary",
      "criticalSuccess": {
        "msg": "events.the-trial.stage-0.criticalSuccess.msg"
      },
      "success": {
        "msg": "events.the-trial.stage-0.success.msg"
      },
      "failure": {
        "msg": "events.the-trial.stage-0.failure.msg"
      },
      "criticalFailure": {
        "msg": "events.the-trial.stage-0.criticalFailure.msg"
      }
    }
  ],
  "resolvedOn": [
    "success",
    "criticalSuccess",
    "criticalFailure"
  ],
  "resolution": "events.the-trial.resolution"
}
