=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/government.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/government.json",
  "title": "Kingdom Government",
  "description": "A Kingdom Government",
  "$ref": "#/$defs/Government",
  "$defs": {
    "Government": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "description",
        "bonusFeat",
        "boosts",
        "freeBoosts",
        "skillProficiencies"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "boosts": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Ability"
          }
        },
        "freeBoosts": {
          "type": "number"
        },
        "skillProficiencies": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/KingdomSkill"
          }
        },
        "bonusFeat": {
          "type": "string"
        }
      }
    },
    "Ability": {
      "type": "string",
      "enum": [
        "stability",
        "culture",
        "economy",
        "loyalty"
      ]
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/governments/Feudalism.json
{
    "id": "feudalism",
    "name": "Feudalism",
    "description": "Your nationâ€™s rule is vested in a dynastic royal family, though much of the real power is distributed among their vassals and fiefdoms.",
    "boosts": [
        "stability",
        "culture"
    ],
    "freeBoosts": 1,
    "bonusFeat": "fortified-fiefs",
    "skillProficiencies": [
        "defense",
        "trade"
    ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/governments/Republic.json
{
    "id": "republic",
    "name": "governments.republic.name",
    "description": "governments.republic.description",
    "boosts": [
        "stability",
        "loyalty"
    ],
    "freeBoosts": 1,
    "bonusFeat": "pull-together",
    "skillProficiencies": [
        "engineering",
        "politics"
    ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/governments/Thaumocracy.json
{
    "id": "thaumocracy",
    "name": "Thaumocracy",
    "description": "Your nation is governed by those most skilled in magic, using their knowledge and power to determine the best ways to rule. While the type of magic wielded by the nation’s rulers can adjust its themes (or even its name—a thaumocracy run by divine spellcasters would be a theocracy, for example), the details below remain the same whether it’s arcane, divine, occult, primal, or any combination of the four.",
    "boosts": [
        "economy",
        "culture"
    ],
    "freeBoosts": 1,
    "bonusFeat": "Practical Magic",
    "skillProficiencies": [
        "folklore",
        "magic"
    ]
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/governments/Despotism.json
{
    "id": "despotism",
    "name": "governments.despotism.name",
    "description": "governments.despotism.description",
    "boosts": [
        "stability",
        "economy"
    ],
    "freeBoosts": 1,
    "bonusFeat": "crush-dissent",
    "skillProficiencies": [
        "intrigue",
        "warfare"
    ]
}
