=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/kingdom-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/kingdom-activity.json",
  "title": "Kingdom Activity",
  "description": "A Kingdom Activity",
  "$ref": "#/$defs/Activity",
  "$defs": {
    "ActivityResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "msg"
      ],
      "properties": {
        "msg": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        }
      }
    },
    "Activity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "title",
        "description",
        "id",
        "dc",
        "skills",
        "phase",
        "enabled",
        "fortune",
        "oncePerRound"
      ],
      "properties": {
        "skills": {
          "$ref": "#/$defs/Skills"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "requirement": {
          "type": "string"
        },
        "special": {
          "type": "string"
        },
        "dc": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "string",
              "enum": [
                "control",
                "custom",
                "none",
                "scouting"
              ]
            }
          ]
        },
        "phase": {
          "type": "string",
          "enum": [
            "army",
            "civic",
            "commerce",
            "event",
            "leadership",
            "region",
            "upkeep"
          ]
        },
        "dcAdjustment": {
          "type": "number"
        },
        "enabled": {
          "type": "boolean"
        },
        "fortune": {
          "type": "boolean"
        },
        "oncePerRound": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "hint": {
          "type": "object"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityResult"
        },
        "success": {
          "$ref": "#/$defs/ActivityResult"
        },
        "failure": {
          "$ref": "#/$defs/ActivityResult"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityResult"
        }
      }
    },
    "Modifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "value",
        "name",
        "enabled"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "proficiency",
            "item",
            "status",
            "circumstance",
            "vacancy",
            "untyped",
            "leadership"
          ]
        },
        "value": {
          "type": "number"
        },
        "predicatedValue": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/WhenPredicate"
          }
        },
        "name": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "turns": {
          "type": "number"
        },
        "isConsumedAfterRoll": {
          "type": "boolean"
        },
        "rollOptions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "predicates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "Predicate": {
      "oneOf": [
        {
          "$ref": "#/$defs/GtePredicate"
        },
        {
          "$ref": "#/$defs/GtPredicate"
        },
        {
          "$ref": "#/$defs/LtePredicate"
        },
        {
          "$ref": "#/$defs/LtPredicate"
        },
        {
          "$ref": "#/$defs/EqPredicate"
        },
        {
          "$ref": "#/$defs/OrPredicate"
        },
        {
          "$ref": "#/$defs/AndPredicate"
        },
        {
          "$ref": "#/$defs/NotPredicate"
        },
        {
          "$ref": "#/$defs/HasFlagPredicate"
        },
        {
          "$ref": "#/$defs/HasRollOptionPredicate"
        },
        {
          "$ref": "#/$defs/InPredicate"
        }
      ]
    },
    "InPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "in"
      ],
      "properties": {
        "in": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gte"
      ],
      "properties": {
        "gte": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gt"
      ],
      "properties": {
        "gt": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "LtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lte"
      ],
      "properties": {
        "lte": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "LtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lt"
      ],
      "properties": {
        "lt": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "EqPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "eq"
      ],
      "properties": {
        "eq": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "OrPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "or"
      ],
      "properties": {
        "or": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "AndPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "and"
      ],
      "properties": {
        "and": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "NotPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "not"
      ],
      "properties": {
        "not": {
          "$ref": "#/$defs/Predicate"
        }
      }
    },
    "HasFlagPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasFlag"
      ],
      "properties": {
        "hasFlag": {
          "type": "string"
        }
      }
    },
    "HasRollOptionPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasRollOption"
      ],
      "properties": {
        "hasRollOption": {
          "type": "string"
        }
      }
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "WhenPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "when"
      ],
      "properties": {
        "when": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/Predicate"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "Skills": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "agriculture": {
          "type": "number"
        },
        "arts": {
          "type": "number"
        },
        "boating": {
          "type": "number"
        },
        "defense": {
          "type": "number"
        },
        "engineering": {
          "type": "number"
        },
        "exploration": {
          "type": "number"
        },
        "folklore": {
          "type": "number"
        },
        "industry": {
          "type": "number"
        },
        "intrigue": {
          "type": "number"
        },
        "magic": {
          "type": "number"
        },
        "politics": {
          "type": "number"
        },
        "scholarship": {
          "type": "number"
        },
        "statecraft": {
          "type": "number"
        },
        "trade": {
          "type": "number"
        },
        "warfare": {
          "type": "number"
        },
        "wilderness": {
          "type": "number"
        }
      }
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Provide Care.json
{
    "id": "provide-care",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "leadership",
    "dc": "control",
    "title": "Provide Care",
    "description": "Attempt a basic check to organize and encourage your settlements’ healers, apothecaries, medics, and other caregivers to provide care and support for citizens in need.",
    "skills": {
        "defense": 0
    },
    "criticalSuccess": {
        "msg": "You provide unexpectedly compassionate support for the people. @lose1Unrest and reduce one Ruin of your choice by 1: <ul><li>@lose1Corruption</li><li>@lose1Crime</li><li>@lose1Decay</li><li>@lose1Strife</li></ul>"
    },
    "success": {
        "msg": "Your care soothes the worries and fears of the populace; @lose1Unrest."
    },
    "failure": {
        "msg": "You don’t provide any notable care for the citizens, but at least you don’t make things worse."
    },
    "criticalFailure": {
        "msg": "Your attempt to provide care backfires. @gain1Unrest or a Ruin of your choice by 1: <ul><li>@gain1Corruption</li><li>@gain1Crime</li><li>@gain1Decay</li><li>@gain1Strife</li></ul>"
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Recover Army Lost.json
{
  "id": "recover-army-lost",
  "oncePerRound": false,
  "fortune": false,
  "enabled": true,
  "phase": "army",
  "dc": "control",
  "title": "activities.recover-army-lost.title",
  "description": "activities.recover-army-lost.description",
  "skills": {
    "exploration": 0,
    "wilderness": 2
  },
  "criticalSuccess": {
    "msg": "activities.recover-army-lost.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.recover-army-lost.success.msg"
  },
  "failure": {
    "msg": "activities.recover-army-lost.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.recover-army-lost.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Outfit Army.json
{
  "id": "outfit-army",
  "oncePerRound": false,
  "fortune": false,
  "enabled": true,
  "phase": "army",
  "dc": "control",
  "title": "activities.outfit-army.title",
  "description": "activities.outfit-army.description",
  "skills": {
    "trade": 0,
    "warfare": 0
  },
  "criticalSuccess": {
    "msg": "activities.outfit-army.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.outfit-army.success.msg"
  },
  "failure": {
    "msg": "activities.outfit-army.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.outfit-army.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Establish Settlement.json
{
    "id": "establish-settlement",
    "title": "Establish Settlement",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "region",
    "dc": "control",
    "description": "You draw up plans, gather resources, entice citizens, and establish boundaries to found a brand new settlement in the hex. Attempt a basic Engineering, Industry, Politics, or Scholarship check. If you cannot pay the RP required by the result of this check, treat your result as a critical failure. A settlement always starts as a village.",
    "requirement": "The hex in which you’re establishing the settlement has been Cleared and doesn’t currently have a settlement (including a Freehold) in it.",
    "skills": {
        "engineering": 0,
        "industry": 0,
        "politics": 0,
        "scholarship": 0
    },
    "criticalSuccess": {
        "msg": "You establish the settlement largely with the aid of enthusiastic volunteers. @lose1d6ResourcePoints"
    },
    "success": {
        "msg": "You establish the settlement. @lose3d6ResourcePoints"
    },
    "failure": {
        "msg": "You establish the settlement, but inefficiently and at great expense. @lose6d6ResourcePoints"
    },
    "criticalFailure": {
        "msg": "You fail to establish the settlement."
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Recover Army: Lost.json
{
    "id": "recover-army-lost",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "army",
    "dc": "control",
    "title": "Recover Army: Lost",
    "description": "When an army endures ill fortune, it can become afflicted by negative conditions. You can use the Recover Army activity to work at removing an affliction with a basic skill check.",
    "skills": {
        "exploration": 0,
        "wilderness": 2
    },
    "criticalSuccess": {
        "msg": "You remove the affliction."
    },
    "success": {
        "msg": "You remove the affliction."
    },
    "failure": {
        "msg": "You fail to remove the affliction."
    },
    "criticalFailure": {
        "msg": "You fail to remove the affliction and your soldierâ€™s lowered morale spreads discontent; @gain1Unrest."
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Build Roads.json
{
    "id": "build-roads",
    "title": "Build Roads",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "region",
    "dc": "control",
    "description": "<p>You order your kingdom’s engineers to construct a network of robust roads through the hex. Travel along roads uses a terrain type one step better than the surrounding terrain; for example, roads through forest hexes—normally difficult terrain—allow travel as if it were open terrain.</p>\n<p>Spend RP as determined by the hex’s most inhospitable terrain (if the hex includes any rivers that cross the hex from one hex side to any other, you must spend double the normal RP cost to also build bridges; this adds the Bridge structure to that hex):</p>\n<ul>\n<li><b>Mountains</b>: <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"12\">Lose 12 Resource Points</button></li>\n<li><b>Swamps</b>: <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"8\">Lose 8 Resource Points</button></li>\n<li><b>Forests</b>: <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"4\">Lose 4 Resource Points</button></li>\n<li><b>Hills</b>: <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"2\">Lose 2 Resource Points</button></li>\n<li><b>Plains</b>: <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Lose 1 Resource Points</button></li>\n</ul>\n<p>Then attempt a basic check. Work with the GM to determine where your roads appear on the map.</p>",
    "requirement": "The hex in which you seek to build roads must be claimed by your kingdom.",
    "skills": {
        "engineering": 0
    },
    "criticalSuccess": {
        "msg": "You build roads into the target hex and, if possible, one adjacent claimed hex that doesn’t yet have roads and whose terrain features are at least as hospitable as those of the target hex"
    },
    "success": {
        "msg": "You build roads in the hex."
    },
    "failure": {
        "msg": "You fail to build roads in the hex."
    },
    "criticalFailure": {
        "msg": "Your attempt to build roads ends in disaster. Not only do you fail to build roads, but you lose several workers to an accident, banditry, a vicious monster, or some other unforeseen occurrence. <button type=\"button\" class=\"km-gain-lose\" data-type=\"unrest\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Unrest</button>"
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Capital Investment.json
{
    "id": "capital-investment",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "leadership",
    "dc": "control",
    "title": "Capital Investment",
    "description": "You contribute funds from your personal wealth for the good of the kingdom, including coinage, gems, jewelry, weapons and armor salvaged from enemies, magical or alchemical items, and so on. Your contribution generates economic activity in the form of RP that can be used during your current Kingdom turn or on the next Kingdom turn (your choice).You can use Capital Investment to repay funds from Tap Treasury (page 528). In this case, no roll is needed and you simply deduct the appropriate amount of funds from your personal wealth to pay back that which was borrowed. When you use Capital Investment to generate RP, the amount of gp required to make an investment is set by your kingdom’s level. Investments below this amount cause your attempt at Capital Investment to suffer an automatic critical failure, while investments above this amount are lost. The investment required is equal to the value listed on Table 10–9: Party Treasure by Level @UUID[Compendium.pf2e.journals.S55aqwWIzpQRFhcq.JournalEntryPage.Ly8l2GT6dbvuY3A2]{Treasure}; use the value for your kingdom’s level under the “Currency per Additional PC” as the required investment value. This is a basic check.",
    "requirement": "You must be within the influence of a settlement that contains at least one Bank.",
    "skills": {
        "trade": 0
    },
    "criticalSuccess": {
        "msg": "Success Your kingdom reaps the benefits of your investment. <button type=\"button\" class=\"km-gain-lose\" data-type=\"rolled-resource-dice\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"4\">Gain 4 Rolled Resource Dice</button>"
    },
    "success": {
        "msg": "Your investment helps the economy. <button type=\"button\" class=\"km-gain-lose\" data-type=\"rolled-resource-dice\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"2\">Gain 2 Rolled Resource Dice</button>"
    },
    "failure": {
        "msg": "Your investment ends up being used to shore up shortfalls elsewhere. <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1d4\">Gain 1d4 Resource Points</button>"
    },
    "criticalFailure": {
        "msg": "Your investment is embezzled, lost, or otherwise misappropriated. Choose one of the following: either <button type=\"button\" class=\"km-gain-lose\" data-type=\"rolled-resource-dice\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Rolled Resource Dice</button> and also increase your Crime by an equal amount, or gain 0 RP and <button type=\"button\" class=\"km-gain-lose\" data-type=\"crime\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Crime</button>"
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Recover Army: Weary.json
{
  "id": "recover-army-weary",
  "oncePerRound": false,
  "fortune": false,
  "enabled": true,
  "phase": "army",
  "dc": "control",
  "title": "activities.recover-army-weary.title",
  "description": "activities.recover-army-weary.description",
  "skills": {
    "defense": 0,
    "arts": 2
  },
  "criticalSuccess": {
    "msg": "activities.recover-army-weary.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.recover-army-weary.success.msg"
  },
  "failure": {
    "msg": "activities.recover-army-weary.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.recover-army-weary.criticalFailure.msg"
  }
}
