=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/kingdom-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/kingdom-activity.json",
  "title": "Kingdom Activity",
  "description": "A Kingdom Activity",
  "$ref": "#/$defs/Activity",
  "$defs": {
    "ActivityResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "msg"
      ],
      "properties": {
        "msg": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        }
      }
    },
    "Activity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "title",
        "description",
        "id",
        "dc",
        "skills",
        "phase",
        "enabled",
        "fortune",
        "oncePerRound"
      ],
      "properties": {
        "skills": {
          "$ref": "#/$defs/Skills"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "requirement": {
          "type": "string"
        },
        "special": {
          "type": "string"
        },
        "dc": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "string",
              "enum": [
                "control",
                "custom",
                "none",
                "scouting"
              ]
            }
          ]
        },
        "phase": {
          "type": "string",
          "enum": [
            "army",
            "civic",
            "commerce",
            "event",
            "leadership",
            "region",
            "upkeep"
          ]
        },
        "dcAdjustment": {
          "type": "number"
        },
        "enabled": {
          "type": "boolean"
        },
        "fortune": {
          "type": "boolean"
        },
        "oncePerRound": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "hint": {
          "type": "object"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityResult"
        },
        "success": {
          "$ref": "#/$defs/ActivityResult"
        },
        "failure": {
          "$ref": "#/$defs/ActivityResult"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityResult"
        }
      }
    },
    "Modifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "value",
        "name",
        "enabled"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "proficiency",
            "item",
            "status",
            "circumstance",
            "vacancy",
            "untyped",
            "leadership"
          ]
        },
        "value": {
          "type": "number"
        },
        "predicatedValue": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/WhenPredicate"
          }
        },
        "name": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "turns": {
          "type": "number"
        },
        "isConsumedAfterRoll": {
          "type": "boolean"
        },
        "rollOptions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "predicates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "Predicate": {
      "oneOf": [
        {
          "$ref": "#/$defs/GtePredicate"
        },
        {
          "$ref": "#/$defs/GtPredicate"
        },
        {
          "$ref": "#/$defs/LtePredicate"
        },
        {
          "$ref": "#/$defs/LtPredicate"
        },
        {
          "$ref": "#/$defs/EqPredicate"
        },
        {
          "$ref": "#/$defs/OrPredicate"
        },
        {
          "$ref": "#/$defs/AndPredicate"
        },
        {
          "$ref": "#/$defs/NotPredicate"
        },
        {
          "$ref": "#/$defs/HasFlagPredicate"
        },
        {
          "$ref": "#/$defs/HasRollOptionPredicate"
        },
        {
          "$ref": "#/$defs/InPredicate"
        }
      ]
    },
    "InPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "in"
      ],
      "properties": {
        "in": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gte"
      ],
      "properties": {
        "gte": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gt"
      ],
      "properties": {
        "gt": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "LtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lte"
      ],
      "properties": {
        "lte": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "LtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lt"
      ],
      "properties": {
        "lt": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "EqPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "eq"
      ],
      "properties": {
        "eq": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "OrPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "or"
      ],
      "properties": {
        "or": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "AndPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "and"
      ],
      "properties": {
        "and": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "NotPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "not"
      ],
      "properties": {
        "not": {
          "$ref": "#/$defs/Predicate"
        }
      }
    },
    "HasFlagPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasFlag"
      ],
      "properties": {
        "hasFlag": {
          "type": "string"
        }
      }
    },
    "HasRollOptionPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasRollOption"
      ],
      "properties": {
        "hasRollOption": {
          "type": "string"
        }
      }
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "WhenPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "when"
      ],
      "properties": {
        "when": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/Predicate"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "Skills": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "agriculture": {
          "type": "number"
        },
        "arts": {
          "type": "number"
        },
        "boating": {
          "type": "number"
        },
        "defense": {
          "type": "number"
        },
        "engineering": {
          "type": "number"
        },
        "exploration": {
          "type": "number"
        },
        "folklore": {
          "type": "number"
        },
        "industry": {
          "type": "number"
        },
        "intrigue": {
          "type": "number"
        },
        "magic": {
          "type": "number"
        },
        "politics": {
          "type": "number"
        },
        "scholarship": {
          "type": "number"
        },
        "statecraft": {
          "type": "number"
        },
        "trade": {
          "type": "number"
        },
        "warfare": {
          "type": "number"
        },
        "wilderness": {
          "type": "number"
        }
      }
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Repair Reputation Strife.json
{
    "id": "repair-reputation-strife",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "leadership",
    "dc": "control",
    "dcAdjustment": 2,
    "title": "Repair Reputation Strife",
    "description": "When things have gotten out of hand in the kingdom and the nationâ€™s reputation has become damaged, you can focus efforts on a campaign to reassure the citizens and bring them closer together, stamp down crime, organize repairs and maintenance of public structures, or strive to adjust poor public opinions.The skill used to Repair Reputation depends on which Ruin total you wish to reduce. If you wish to reduce your Corruption, you attempt an Arts check. If you wish to reduce your Crime, you attempt a Trade check. If you wish to reduce your Decay, you attempt an Engineering check. If you wish to reduce your Strife, you attempt an Intrigue check. In all cases, the DC is your Control DC + 2.",
    "skills": {
        "intrigue": 1
    },
    "criticalSuccess": {
        "msg": "<button type=\"button\" class=\"km-gain-lose\" data-type=\"strife\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"2\">Lose 2 Strife</button> and reduce its current ruin penalty by 1 to a minimum of 0."
    },
    "success": {
        "msg": "<button type=\"button\" class=\"km-gain-lose\" data-type=\"strife\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Lose 1 Strife</button>"
    },
    "failure": {
        "msg": "You fail to reduce the targeted Ruin. You cannot attempt to Repair Reputation on this Ruin for 1 Kingdom turn."
    },
    "criticalFailure": {
        "msg": "You fail to reduce the targeted Ruin in a particularly public and embarrassing way. @gain1d4Unrest, and you cannot attempt to Repair Reputation for 3 Kingdom turns."
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Repair the Flooded Mine.json
{
  "id": "repair-the-flooded-mine",
  "oncePerRound": false,
  "fortune": false,
  "enabled": false,
  "phase": "leadership",
  "dc": 32,
  "title": "activities.repair-the-flooded-mine.title",
  "description": "activities.repair-the-flooded-mine.description",
  "skills": {
    "engineering": 3
  },
  "criticalSuccess": {
    "msg": "activities.repair-the-flooded-mine.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.repair-the-flooded-mine.success.msg"
  },
  "failure": {
    "msg": "activities.repair-the-flooded-mine.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.repair-the-flooded-mine.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Recover Army: Damaged.json
{
    "id": "recover-army-damaged",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "army",
    "dc": "control",
    "title": "Recover Army: Damaged",
    "description": "When an army endures ill fortune, it can become afflicted by negative conditions. You can use the Recover Army activity to work at removing an affliction with a basic skill check.",
    "skills": {
        "defense": 0,
        "folklore": 2
    },
    "criticalSuccess": {
        "msg": "You increase its HP by 2 up to its maximum."
    },
    "success": {
        "msg": "You increase its HP by 1 up to its maximum."
    },
    "failure": {
        "msg": "You fail to remove the affliction. "
    },
    "criticalFailure": {
        "msg": "You fail to remove the affliction and your soldierâ€™s lowered morale spreads discontent; <button type=\"button\" class=\"km-gain-lose\" data-type=\"unrest\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Unrest</button>."
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Show of Force.json
{
  "id": "show-of-force",
  "oncePerRound": false,
  "fortune": false,
  "enabled": false,
  "phase": "leadership",
  "dc": "control",
  "title": "activities.show-of-force.title",
  "description": "activities.show-of-force.description",
  "skills": {
    "warfare": 0
  },
  "criticalSuccess": {
    "msg": "activities.show-of-force.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.show-of-force.success.msg"
  },
  "failure": {
    "msg": "activities.show-of-force.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.show-of-force.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Harvest Lily Pollen.json
{
  "id": "harvest-lily-pollen",
  "oncePerRound": false,
  "fortune": false,
  "enabled": false,
  "phase": "region",
  "dc": "control",
  "title": "activities.harvest-lily-pollen.title",
  "description": "activities.harvest-lily-pollen.description",
  "skills": {
    "agriculture": 3
  },
  "criticalSuccess": {
    "msg": "activities.harvest-lily-pollen.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.harvest-lily-pollen.success.msg"
  },
  "failure": {
    "msg": "activities.harvest-lily-pollen.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.harvest-lily-pollen.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Fortify Hex (V&K).json
{
    "id": "fortify-hex-vk",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "region",
    "dc": "control",
    "title": "Fortify Hex (V&K)",
    "description": "<p>Your command your engineers to construct a protected encampment, such as a fort or barbican, to serve as a defensive post in the hex. Spend RP as determined by the hexâ€™s most inhospitable terrain:</p>\n<ul>\n<li><b>Mountains</b>: @lose12ResourcePoints</li>\n<li><b>Swamps</b>: @lose8ResourcePoints</li>\n<li><b>Forests</b>: @lose4ResourcePoints</li>\n<li><b>Hills</b>: @lose2ResourcePoints</li>\n<li><b>Plains</b>: @lose1ResourcePoints</li>\n</ul>\n<p>Then attempt a basic check. A fortified hex grants an additional bonus in warfare, but also gives traveling PCs a place to rest that prevents wandering monsters from interrupting their rest.</p>\n<p>The Fortify Hex Activity gives a Hex the Refuge terrain feature. If a Settlement is later established in the Hex, the GM may allow the Refuge to be converted to a free or discounted appropriate Structure, such as a Barracks. Any free Structure should not exceed one Resource Die. For a discounted Structure, the GM can choose how much to discount it but the discount should not be more than one Resource Die and/or two Commodities. The Kingdom must pay any remaining RP and Commodities. The new settlement then starts with the Structure.</p>",
    "requirement": "The target hex must be claimed by your kingdom and must not have a settlement in it.",
    "skills": {
        "defense": 0
    },
    "criticalSuccess": {
        "msg": "You find a defensible position for your fortification and finish construction efficiently. Gain a refund of half the RP you spent to build in the hex, then @lose1Unrest"
    },
    "success": {
        "msg": "You establish your fortification in the hex. @lose1Unrest"
    },
    "failure": {
        "msg": "You fail to fortify the hex."
    },
    "criticalFailure": {
        "msg": "Your attempt ends in disaster. Not only do you fail to build a structure, but you lose several workers to an accident, banditry, a vicious monster, or some other unforeseen occurrence. @gain1Unrest"
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Creative Solution.json
{
    "id": "creative-solution",
    "enabled": true,
    "oncePerRound": false,
    "fortune": true,
    "phase": "leadership",
    "dc": "control",
    "title": "Creative Solution",
    "description": "You work with your kingdom’s scholars, thinkers, and practitioners of magical and mundane experimentation to come up with new ways to resolve issues when business as usual is just not working. Attempt a basic check.",
    "skills": {
        "scholarship": 0
    },
    "criticalSuccess": {
        "msg": "You can call upon the solution to aid in resolving any Kingdom skill check made during the remainder of this Kingdom turn <button type=\"button\" class=\"km-gain-lose\" data-type=\"creative-solution\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Creative Solution</button>. Do so when a Kingdom skill check is rolled, but before you learn the result. Immediately reroll that check with a +2 circumstance bonus; you must take the new result. If you don’t use your Creative Solution by the end of this turn, you lose this benefit and gain 10XP instead.",
        "modifiers": [
            {
                "turns": 1,
                "enabled": false,
                "value": 2,
                "name": "Creative Solution: Critical Success",
                "type": "circumstance",
                "isConsumedAfterRoll": true
            }
        ]
    },
    "success": {
        "msg": "You can call upon the solution to aid in resolving any Kingdom skill check made during the remainder of this Kingdom turn <button type=\"button\" class=\"km-gain-lose\" data-type=\"creative-solution\" data-mode=\"gain\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1\">Gain 1 Creative Solution</button>. Do so when a Kingdom skill check is rolled, but before you learn the result. Immediately reroll that check with a +2 circumstance bonus; you must take the new result. If you don’t use your Creative Solution by the end of this turn, you lose this benefit and gain 10XP instead. In addition, <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"1d4\">Lose 1d4 Resource Points</button> to research the solution. This cost is paid now, whether or not you use your Creative Solution.",
        "modifiers": [
            {
                "turns": 1,
                "enabled": false,
                "value": 2,
                "name": "Creative Solution: Success",
                "type": "circumstance",
                "isConsumedAfterRoll": true
            }
        ]
    },
    "failure": {
        "msg": "Your attempt at researching is a failure and you <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"2d6\">Lose 2d6 Resource Points</button>. It provides no advantage."
    },
    "criticalFailure": {
        "msg": "Your attempt at researching is a failure and you <button type=\"button\" class=\"km-gain-lose\" data-type=\"resource-points\" data-mode=\"lose\" data-turn=\"now\" data-multiple=\"false\" data-value=\"2d6\">Lose 2d6 Resource Points</button>. It provides no advantage. In addition, your scholars and thinkers are so frustrated that you take a –1 circumstance penalty to Culture-based checks until the end of the next Kingdom turn.",
        "modifiers": [
            {
                "turns": 2,
                "enabled": true,
                "value": -1,
                "name": "Creative Solution: Critical Failure",
                "type": "circumstance",
                "predicates": [
                    {
                        "eq": [
                            "@ability",
                            "culture"
                        ]
                    }
                ]
            }
        ]
    },
    "special": "You cannot influence a check with Supernatural Solution and Creative Solution simultaneously."
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Recover Army: Mired or Pinned.json
{
    "id": "recover-army-mired-pinned",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "army",
    "dc": "control",
    "title": "Recover Army: Mired or Pinned",
    "description": "When an army endures ill fortune, it can become afflicted by negative conditions. You can use the Recover Army activity to work at removing an affliction with a basic skill check.",
    "skills": {
        "engineering": 0,
        "magic": 2
    },
    "criticalSuccess": {
        "msg": "You reduce the affliction’s value by 2. If the affliction does not have a value, it is removed."
    },
    "success": {
        "msg": "As critical success but you reduce the affliction’s value by 1."
    },
    "failure": {
        "msg": "You fail to remove the affliction."
    },
    "criticalFailure": {
        "msg": "You fail to remove the affliction and your soldier’s lowered morale spreads discontent; @gain1Unrest."
    }
}
