=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/kingdom-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/kingdom-activity.json",
  "title": "Kingdom Activity",
  "description": "A Kingdom Activity",
  "$ref": "#/$defs/Activity",
  "$defs": {
    "ActivityResult": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "msg"
      ],
      "properties": {
        "msg": {
          "type": "string"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Modifier"
          }
        }
      }
    },
    "Activity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "title",
        "description",
        "id",
        "dc",
        "skills",
        "phase",
        "enabled",
        "fortune",
        "oncePerRound"
      ],
      "properties": {
        "skills": {
          "$ref": "#/$defs/Skills"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "requirement": {
          "type": "string"
        },
        "special": {
          "type": "string"
        },
        "dc": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "string",
              "enum": [
                "control",
                "custom",
                "none",
                "scouting"
              ]
            }
          ]
        },
        "phase": {
          "type": "string",
          "enum": [
            "army",
            "civic",
            "commerce",
            "event",
            "leadership",
            "region",
            "upkeep"
          ]
        },
        "dcAdjustment": {
          "type": "number"
        },
        "enabled": {
          "type": "boolean"
        },
        "fortune": {
          "type": "boolean"
        },
        "oncePerRound": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "hint": {
          "type": "object"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityResult"
        },
        "success": {
          "$ref": "#/$defs/ActivityResult"
        },
        "failure": {
          "$ref": "#/$defs/ActivityResult"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityResult"
        }
      }
    },
    "Modifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "value",
        "name",
        "enabled"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "proficiency",
            "item",
            "status",
            "circumstance",
            "vacancy",
            "untyped",
            "leadership"
          ]
        },
        "value": {
          "type": "number"
        },
        "predicatedValue": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/WhenPredicate"
          }
        },
        "name": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "turns": {
          "type": "number"
        },
        "isConsumedAfterRoll": {
          "type": "boolean"
        },
        "rollOptions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "predicates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "Predicate": {
      "oneOf": [
        {
          "$ref": "#/$defs/GtePredicate"
        },
        {
          "$ref": "#/$defs/GtPredicate"
        },
        {
          "$ref": "#/$defs/LtePredicate"
        },
        {
          "$ref": "#/$defs/LtPredicate"
        },
        {
          "$ref": "#/$defs/EqPredicate"
        },
        {
          "$ref": "#/$defs/OrPredicate"
        },
        {
          "$ref": "#/$defs/AndPredicate"
        },
        {
          "$ref": "#/$defs/NotPredicate"
        },
        {
          "$ref": "#/$defs/HasFlagPredicate"
        },
        {
          "$ref": "#/$defs/HasRollOptionPredicate"
        },
        {
          "$ref": "#/$defs/InPredicate"
        }
      ]
    },
    "InPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "in"
      ],
      "properties": {
        "in": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gte"
      ],
      "properties": {
        "gte": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "GtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gt"
      ],
      "properties": {
        "gt": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "LtePredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lte"
      ],
      "properties": {
        "lte": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "LtPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "lt"
      ],
      "properties": {
        "lt": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "EqPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "eq"
      ],
      "properties": {
        "eq": {
          "type": "array",
          "prefixItems": [
            {
              "type": "string"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "OrPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "or"
      ],
      "properties": {
        "or": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "AndPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "and"
      ],
      "properties": {
        "and": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Predicate"
          }
        }
      }
    },
    "NotPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "not"
      ],
      "properties": {
        "not": {
          "$ref": "#/$defs/Predicate"
        }
      }
    },
    "HasFlagPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasFlag"
      ],
      "properties": {
        "hasFlag": {
          "type": "string"
        }
      }
    },
    "HasRollOptionPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "hasRollOption"
      ],
      "properties": {
        "hasRollOption": {
          "type": "string"
        }
      }
    },
    "KingdomSkill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "WhenPredicate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "when"
      ],
      "properties": {
        "when": {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/Predicate"
            },
            {
              "type": "string"
            }
          ],
          "items": false,
          "minItems": 2
        }
      }
    },
    "Skills": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "agriculture": {
          "type": "number"
        },
        "arts": {
          "type": "number"
        },
        "boating": {
          "type": "number"
        },
        "defense": {
          "type": "number"
        },
        "engineering": {
          "type": "number"
        },
        "exploration": {
          "type": "number"
        },
        "folklore": {
          "type": "number"
        },
        "industry": {
          "type": "number"
        },
        "intrigue": {
          "type": "number"
        },
        "magic": {
          "type": "number"
        },
        "politics": {
          "type": "number"
        },
        "scholarship": {
          "type": "number"
        },
        "statecraft": {
          "type": "number"
        },
        "trade": {
          "type": "number"
        },
        "warfare": {
          "type": "number"
        },
        "wilderness": {
          "type": "number"
        }
      }
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Disband Army.json
{
    "id": "disband-army",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "army",
    "dc": "none",
    "title": "Disband Army",
    "description": "You can choose to disband an army with no check needed. If the army consisted of conscripts from your kingdom, the soldiers revert to being citizens. If the army was recruited from creatures encountered in the wilds, they return to their homes. A disbanded army no longer contributes to your kingdomâ€™s Consumption.",
    "skills": {
        "agriculture": 0,
        "arts": 0,
        "boating": 0,
        "defense": 0,
        "engineering": 0,
        "exploration": 0,
        "folklore": 0,
        "industry": 0,
        "intrigue": 0,
        "magic": 0,
        "politics": 0,
        "scholarship": 0,
        "statecraft": 0,
        "trade": 0,
        "warfare": 0,
        "wilderness": 0
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Recruit Army.json
{
    "id": "recruit-army",
    "oncePerRound": false,
    "fortune": false,
    "enabled": true,
    "phase": "leadership",
    "dc": "custom",
    "title": "Recruit Army",
    "description": "Either you recruit an army from your kingdom’s citizens, or you secure the allegiance of a specialized army you encountered. If you’re recruiting an army from your kingdom’s citizens, choose one of the basic armies listed at the start of page 570 and attempt a Warfare check against the army’s Recruitment DC. If you’re securing a specialized army, you must attempt a Statecraft check against the Recruitment DC;",
    "skills": {
        "warfare": 0,
        "statecraft": 0
    },
    "criticalSuccess": {
        "msg": "You recruit the army; it becomes efficient."
    },
    "success": {
        "msg": "You recruit the army."
    },
    "failure": {
        "msg": "You fail to recruit the army."
    },
    "criticalFailure": {
        "msg": "Many of the individuals in the army you attempted to recruit took offense at the attempt. @gain1Unrest, and you cannot attempt to recruit an army again until the next Kingdom turn."
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Purchase Commodities.json
{
  "id": "purchase-commodities",
  "oncePerRound": false,
  "fortune": false,
  "enabled": true,
  "phase": "leadership",
  "dc": "control",
  "title": "activities.purchase-commodities.title",
  "description": "activities.purchase-commodities.description",
  "skills": {
    "trade": 0
  },
  "criticalSuccess": {
    "msg": "activities.purchase-commodities.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.purchase-commodities.success.msg"
  },
  "failure": {
    "msg": "activities.purchase-commodities.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.purchase-commodities.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Evangelize the End.json
{
    "id": "evangelize-the-end",
    "oncePerRound": false,
    "fortune": false,
    "enabled": false,
    "phase": "leadership",
    "dc": "control",
    "title": "Evangelize the End",
    "description": "You spend time preaching the End Times. While your sermons certainly aren’t for everyone, your methods avoid deliberately antagonizing those who see hope in the world while simultaneously providing ease and calm to the more desperate among the kingdom’s citizens. Attempt a basic Folklore check to determine how effective your sermons are.",
    "skills": {
        "folklore": 0
    },
    "criticalSuccess": {
        "msg": "Your prayers soothe and calm the more criminal-minded citizens for the time being. @lose1d4Unrest, and either @lose2Crime or @lose1Corruption or @lose1Strife."
    },
    "success": {
        "msg": "Your prayers serve to redirect and calm discord. @lose1d3Unrest"
    },
    "failure": {
        "msg": "Your prayers serve to redirect and calm discord. @lose1Unrest"
    },
    "criticalFailure": {
        "msg": "Your prayers have unsettled some of your citizens. @gain1d4Unrest and @gain1Decay "
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Create a Masterpiece.json
{
    "id": "create-a-masterpiece",
    "oncePerRound": true,
    "fortune": false,
    "enabled": true,
    "phase": "leadership",
    "dc": "control",
    "title": "Create a Masterpiece",
    "description": "You encourage your kingdom’s artists to create and display a masterful work of art to bolster your kingdom’s reputation. Attempt a basic check; the result affects either Fame or Infamy (depending on the type of kingdom you’re running). Create a Masterpiece may be attempted only once per Kingdom turn regardless of the number of leaders pursuing activities.",
    "skills": {
        "arts": 1
    },
    "criticalSuccess": {
        "msg": "@gain1Fame, and @gain1FameNextTurn. @gain2RolledResourceDice"
    },
    "success": {
        "msg": "@gain1Fame"
    },
    "failure": {
        "msg": "Your attempt to create a masterpiece fails."
    },
    "criticalFailure": {
        "msg": "Not only does your attempt to create a masterpiece fail, it does so in a dramatic and humiliating way. @lose1Fame; if you have no Fame or Infamy points to lose, instead @gain1d4Unrest"
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Quell Unrest.json
{
    "id": "quell-unrest",
    "oncePerRound": true,
    "fortune": false,
    "enabled": true,
    "phase": "leadership",
    "dc": "control",
    "title": "Quell Unrest",
    "description": "You send your agents among the citizenry with the charge of suppressing dissent and calming unrest. You can attempt a basic Arts, Folklore, Intrigue, Magic, Politics, or Warfare check to Quell Unrest, but you can never use the same skill for this activity in consecutive Kingdom turns. This activity cannot be attempted more than once per Kingdom turn.",
    "skills": {
        "arts": 0,
        "folklore": 0,
        "intrigue": 0,
        "magic": 0,
        "politics": 0,
        "warfare": 0
    },
    "criticalSuccess": {
        "msg": "@lose1d6Unrest"
    },
    "success": {
        "msg": "@lose1Unrest"
    },
    "failure": {
        "msg": "You fail to reduce Unrest."
    },
    "criticalFailure": {
        "msg": "You not only fail to reduce Unrest, but actually incite further anger among the citizenry. Choose one of the following: @gain1d4Unrest or increase two Ruins of your choice by 1: <ul><li>@gain1Corruption</li><li>@gain1Crime</li><li>@gain1Decay</li><li>@gain1Strife</li></ul>"
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Craft Luxuries.json
{
  "id": "craft-luxuries",
  "oncePerRound": false,
  "fortune": false,
  "enabled": true,
  "phase": "leadership",
  "dc": "control",
  "title": "activities.craft-luxuries.title",
  "description": "activities.craft-luxuries.description",
  "skills": {
    "arts": 0
  },
  "criticalSuccess": {
    "msg": "activities.craft-luxuries.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.craft-luxuries.success.msg"
  },
  "failure": {
    "msg": "activities.craft-luxuries.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.craft-luxuries.criticalFailure.msg"
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/kingdom-activities/Pledge of Fealty.json
{
  "id": "pledge-of-fealty",
  "oncePerRound": false,
  "fortune": false,
  "enabled": true,
  "phase": "leadership",
  "dc": "control",
  "title": "activities.pledge-of-fealty.title",
  "description": "activities.pledge-of-fealty.description",
  "skills": {
    "intrigue": 1,
    "statecraft": 1,
    "warfare": 1
  },
  "criticalSuccess": {
    "msg": "activities.pledge-of-fealty.criticalSuccess.msg"
  },
  "success": {
    "msg": "activities.pledge-of-fealty.success.msg"
  },
  "failure": {
    "msg": "activities.pledge-of-fealty.failure.msg"
  },
  "criticalFailure": {
    "msg": "activities.pledge-of-fealty.criticalFailure.msg"
  }
}
