=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/recipe.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/recipe.json",
  "title": "Recipe",
  "description": "A recipe",
  "$ref": "#/$defs/Recipe",
  "$defs": {
    "Rarity": {
      "type": "string",
      "enum": [
        "common",
        "uncommon",
        "rare",
        "unique"
      ]
    },
    "Recipe": {
      "type": "object",
      "required": [
        "name",
        "basicIngredients",
        "specialIngredients",
        "cookingLoreDC",
        "survivalDC",
        "uuid",
        "level",
        "cost",
        "rarity",
        "criticalSuccess",
        "success",
        "criticalFailure"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "basicIngredients": {
          "type": "number"
        },
        "specialIngredients": {
          "type": "number"
        },
        "cookingLoreDC": {
          "type": "number"
        },
        "survivalDC": {
          "type": "number"
        },
        "uuid": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "cost": {
          "type": "string"
        },
        "rarity": {
          "$ref": "#/$defs/Rarity"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "success": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "favoriteMeal": {
          "$ref": "#/$defs/CookingOutcome"
        }
      }
    },
    "CookingOutcome": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/MealEffect"
          }
        },
        "chooseRandomly": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Conditions": {
      "type": "object",
      "required": [
        "condition",
        "value"
      ],
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "drained",
            "enfeebled",
            "stupefied",
            "clumsy"
          ]
        },
        "value": {
          "type": "number"
        },
        "afterRest": {
          "type": "boolean"
        }
      }
    },
    "MealEffect": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "changeRestDurationSeconds": {
          "type": "number"
        },
        "reduceConditions": {
          "type": "object",
          "mode": {
            "type": "string",
            "enum": [
              "all",
              "random"
            ]
          },
          "drained": {
            "type": "number"
          },
          "stupefied": {
            "type": "number"
          },
          "clumsy": {
            "type": "number"
          },
          "enfeebled": {
            "type": "number"
          },
          "afterRest": {
            "type": "boolean"
          }
        },
        "doublesHealing": {
          "type": "boolean"
        },
        "halvesHealing": {
          "type": "boolean"
        },
        "healMode": {
          "type": "string",
          "enum": [
            "afterConsumption",
            "afterRest",
            "afterConsumptionAndRest"
          ]
        },
        "healFormula": {
          "type": "string"
        },
        "damageFormula": {
          "type": "string"
        }
      },
      "required": [
        "uuid"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Sweet Pancakes.json
{
  "name": "Sweet Pancakes",
  "icon": "icons/commodities/cloth/cloth-roll-orange.webp",
  "basicIngredients": 2,
  "specialIngredients": 2,
  "cookingLoreDC": 23,
  "survivalDC": 25,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.WrDLx0FVkaglg1hh",
  "level": 7,
  "cost": "18 gp",
  "rarity": "common",
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.BXTnX9xhnYvolrFk"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Lpo0XSUVmGDQaXtz"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.ovbBMpOBtB1CrLOv"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.q5JHZeJeAIscA1ky"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Fish-On-A-Stick.json
{
  "name": "Fish-On-A-Stick",
  "icon": "icons/consumables/food/cooked-kebab-meat-skewer-orange.webp",
  "basicIngredients": 2,
  "specialIngredients": 0,
  "cookingLoreDC": 17,
  "survivalDC": 19,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.b59ro2GHvRvBOko8",
  "level": 1,
  "cost": "1 gp",
  "rarity": "common",
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.8eIGJPWFlg4L94wY"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.L5sACVlUjYP6lJ7q"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "changeRestDurationSeconds": 3600,
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.c9qgXgiAJikyTM0p"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "changeRestDurationSeconds": -3600,
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.dZTQ5rfedrpLUTxE"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Black Linnorm Stew.json
{
  "name": "Black Linnorm Stew",
  "icon": "icons/tools/cooking/bowl-steaming-brown.webp",
  "basicIngredients": 8,
  "specialIngredients": 3,
  "cookingLoreDC": 43,
  "survivalDC": 45,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.V6uIWe6BVFV9Ewo3",
  "level": 18,
  "cost": "1200 gp",
  "rarity": "rare",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.I2LiwNjrowS5u4UG"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.m3FgRCWbVupkaORL"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.s1DfJpXFkJorHsuu"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.sxr0BsJJGeLyNBgq"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Rice-N-Nut Pudding.json
{
  "name": "Rice-N-Nut Pudding",
  "icon": "icons/consumables/food/pot-soup-white.webp",
  "basicIngredients": 2,
  "specialIngredients": 1,
  "cookingLoreDC": 16,
  "survivalDC": 18,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.IrrRh2yttdTDU1A5",
  "level": 2,
  "cost": "2 gp",
  "rarity": "common",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.3Gj0AaUzqwN0CdTi"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.AI1hYVSAMmKgEO9u"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.GzZYeBB1UGMAykXc",
        "removeAfterRest": true
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.IRTWUl4HjRa82A1B"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Jeweled Rice.json
{
  "name": "Jeweled Rice",
  "icon": "icons/commodities/materials/bowl-powder-gold.webp",
  "basicIngredients": 1,
  "specialIngredients": 0,
  "cookingLoreDC": 14,
  "survivalDC": 16,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.N3k7OGUKHn4kTu59",
  "level": 0,
  "cost": "5 sp",
  "rarity": "common",
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.MGFPIxwSgRLvkV71"
      }
    ],
    "message": "The meal was a bit too light; you must eat another meal to stave off starvation."
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.OxEApkXu0hw34Ci5"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Sc5N6l1oCY1oiTfA"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.d8xr0i8GHY4195sa"
      }
    ]
  }
}
