=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/recipe.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/recipe.json",
  "title": "Recipe",
  "description": "A recipe",
  "$ref": "#/$defs/Recipe",
  "$defs": {
    "Rarity": {
      "type": "string",
      "enum": [
        "common",
        "uncommon",
        "rare",
        "unique"
      ]
    },
    "Recipe": {
      "type": "object",
      "required": [
        "name",
        "basicIngredients",
        "specialIngredients",
        "cookingLoreDC",
        "survivalDC",
        "uuid",
        "level",
        "cost",
        "rarity",
        "criticalSuccess",
        "success",
        "criticalFailure"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "basicIngredients": {
          "type": "number"
        },
        "specialIngredients": {
          "type": "number"
        },
        "cookingLoreDC": {
          "type": "number"
        },
        "survivalDC": {
          "type": "number"
        },
        "uuid": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "cost": {
          "type": "string"
        },
        "rarity": {
          "$ref": "#/$defs/Rarity"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "success": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "favoriteMeal": {
          "$ref": "#/$defs/CookingOutcome"
        }
      }
    },
    "CookingOutcome": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/MealEffect"
          }
        },
        "chooseRandomly": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Conditions": {
      "type": "object",
      "required": [
        "condition",
        "value"
      ],
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "drained",
            "enfeebled",
            "stupefied",
            "clumsy"
          ]
        },
        "value": {
          "type": "number"
        },
        "afterRest": {
          "type": "boolean"
        }
      }
    },
    "MealEffect": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "changeRestDurationSeconds": {
          "type": "number"
        },
        "reduceConditions": {
          "type": "object",
          "mode": {
            "type": "string",
            "enum": [
              "all",
              "random"
            ]
          },
          "drained": {
            "type": "number"
          },
          "stupefied": {
            "type": "number"
          },
          "clumsy": {
            "type": "number"
          },
          "enfeebled": {
            "type": "number"
          },
          "afterRest": {
            "type": "boolean"
          }
        },
        "doublesHealing": {
          "type": "boolean"
        },
        "halvesHealing": {
          "type": "boolean"
        },
        "healMode": {
          "type": "string",
          "enum": [
            "afterConsumption",
            "afterRest",
            "afterConsumptionAndRest"
          ]
        },
        "healFormula": {
          "type": "string"
        },
        "damageFormula": {
          "type": "string"
        }
      },
      "required": [
        "uuid"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Chocolate Ice Cream.json
{
  "name": "Chocolate Ice Cream",
  "icon": "icons/tools/laboratory/powder-red.webp",
  "basicIngredients": 2,
  "specialIngredients": 1,
  "cookingLoreDC": 19,
  "survivalDC": 21,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.xfIwKyG1pNFp8JbN",
  "level": 4,
  "cost": "5 gp",
  "rarity": "common",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.0QmbpFYAoyzUu1gi"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.9brr5UKBsZcboAOx"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.KqktmooFbYLQQ2S1"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.L85BNpJEFAozA9kW",
        "removeAfterRest": true
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Supernatural Mince Pie.json
{
  "name": "Supernatural Mince Pie",
  "icon": "icons/consumables/food/cheese-round-glowing-yellow.webp",
  "basicIngredients": 8,
  "specialIngredients": 4,
  "cookingLoreDC": 45,
  "survivalDC": 47,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.RmMZWrzgd8Wh8z5H",
  "level": 20,
  "cost": "3500 gp",
  "rarity": "rare",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.69VWFB5UNLau1Rzt"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.OAxcELiLh04BLVvP"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.WVRQf9SLX0iRh3Ur"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.69MQw1WMMlN4hEzb"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.yLf2n65zVocqsl6r"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.sd45BQ4P7BtsYEuP"
      }
    ],
    "chooseRandomly": true
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.72N0nZAAo2iuCGBd"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.iV22sORhjIhWZMKw"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.CQGJi8WiBq0T8Kc6"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.L8HdDXKrfa3gDakt"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.6CjFExnLSe9qij9z"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Af25wacbdYDnFKwM"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.VhzUKWFVrZ7tgcEQ"
      }
    ],
    "chooseRandomly": true
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Wfmt1NvfIqF3gFav"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Seasoned Wings And Thighs.json
{
  "name": "Seasoned Wings And Thighs",
  "icon": "icons/consumables/food/chicken-bird-cooked.webp",
  "basicIngredients": 4,
  "specialIngredients": 2,
  "cookingLoreDC": 30,
  "survivalDC": 32,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.BTKN1IgANoof0tfB",
  "level": 12,
  "cost": "100 gp",
  "rarity": "common",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.uchgkN3hm1T51zfM",
        "removeAfterRest": true
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.JqKhpMXiQCEsDSCw"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.JqKhpMXiQCEsDSCw"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.q3vnRHRBn3HmRhkV",
        "removeAfterRest": true
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.xF0K40VzyjIbbRMA"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Monster Casserole.json
{
  "name": "Monster Casserole",
  "icon": "icons/consumables/food/soup-broth-bowl-tentacle.webp",
  "basicIngredients": 7,
  "specialIngredients": 2,
  "cookingLoreDC": 28,
  "survivalDC": 30,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.gqT2VQGYgDQIMYsW",
  "level": 11,
  "cost": "70 gp",
  "rarity": "common",
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.5GT0JeRjYJc8e5ZA",
        "removeAfterRest": true
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.af6hFeUUfsF1GiX8"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.gNGXKMmJdNQJZode"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.qad6gIwEpQQIkZwQ"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Succulent Sausages.json
{
  "name": "Succulent Sausages",
  "icon": "icons/consumables/food/sausage-bratwurst-mustard-red-yellow.webp",
  "basicIngredients": 3,
  "specialIngredients": 1,
  "cookingLoreDC": 18,
  "survivalDC": 20,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.IZoPx6QH5NRY1HBi",
  "level": 3,
  "cost": "3 gp",
  "rarity": "common",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.EULsp9VffKbWpD0b"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.G0qnixpCakGeHTp1",
        "removeAfterRest": true
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.WDJQpYYx0N91mkO0",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.jseoPPvbPg4Vr7MI"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Hearty Purple Soup.json
{
  "name": "Hearty Purple Soup",
  "icon": "icons/tools/laboratory/mortar-liquid-pink.webp",
  "basicIngredients": 6,
  "specialIngredients": 3,
  "cookingLoreDC": 40,
  "survivalDC": 42,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.yAB0s5JgzCZpf0dT",
  "level": 16,
  "cost": "500 gp",
  "rarity": "rare",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.6RjaP1s58ITIVn6u"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Zn0CB7bL7vHrMNTU"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.hLGCjXajAYEcII9J"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.o6F8QZbTvt9os8Ni"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.TQXXVzD1ZZHnouTI"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.SJvEGeMryIekwIKk"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Hunter's Roast.json
{
  "name": "Hunter's Roast",
  "icon": "icons/consumables/food/plate-chicken-grilled-mushroom-brown.webp",
  "basicIngredients": 4,
  "specialIngredients": 0,
  "cookingLoreDC": 22,
  "survivalDC": 24,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.5QyW0eFSJRgmyRzU",
  "level": 6,
  "cost": "13 gp",
  "rarity": "common",
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.0un8LMe7iv59He25",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.LiXnKWPOkDBZRpLE"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.RzOGQxp3VHlpYtWJ",
        "removeAfterRest": true,
        "damageFormula": "2d6[poison]",
        "healMode": "afterConsumption"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.zuPWMtCTzuD96Ykz"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Cheese Crostata.json
{
  "name": "Cheese Crostata",
  "icon": "icons/consumables/food/cheese-wheel-round-yellow.webp",
  "basicIngredients": 4,
  "specialIngredients": 0,
  "cookingLoreDC": 22,
  "survivalDC": 24,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.GAf8W01ppdseIGbq",
  "level": 5,
  "cost": "8 gp",
  "rarity": "uncommon",
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.1VchCdA1LMBhYENe"
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.2c2nrlkL2XJXXQIA"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.EBa9BjdANCMLKMEy",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.MI6MF3R5OswdGBUd"
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.X7fTfenq4TukJJM4"
      }
    ]
  }
}
