=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/structure.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/structure.json",
  "title": "Structure",
  "description": "A list of structures",
  "$ref": "#/$defs/Structure",
  "$defs": {
    "Structure": {
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "lots"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "stacksWith": {
          "type": "string"
        },
        "construction": {
          "$ref": "#/$defs/Construction"
        },
        "notes": {
          "type": "string"
        },
        "preventItemLevelPenalty": {
          "type": "boolean"
        },
        "enableCapitalInvestment": {
          "type": "boolean"
        },
        "skillBonusRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SkillBonusRule"
          }
        },
        "activityBonusRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityBonusRule"
          }
        },
        "availableItemsRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AvailableItemsRule"
          }
        },
        "settlementEventRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SettlementEventsRule"
          }
        },
        "leadershipActivityRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/LeadershipActivityRule"
          }
        },
        "storage": {
          "$ref": "#/$defs/CommodityStorage"
        },
        "increaseLeadershipActivities": {
          "type": "boolean"
        },
        "isBridge": {
          "type": "boolean"
        },
        "consumptionReduction": {
          "type": "number"
        },
        "unlockActivities": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "traits": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/BuildingTrait"
          }
        },
        "lots": {
          "type": "number"
        },
        "affectsEvents": {
          "type": "boolean"
        },
        "affectsDowntime": {
          "type": "boolean"
        },
        "reducesUnrest": {
          "type": "boolean"
        },
        "reducesRuin": {
          "type": "boolean"
        },
        "level": {
          "type": "number"
        },
        "upgradeFrom": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "reduceUnrestBy": {
          "$ref": "#/$defs/ReduceUnrestBy"
        },
        "reduceRuinBy": {
          "$ref": "#/$defs/RuinAmount"
        },
        "gainRuin": {
          "$ref": "#/$defs/RuinAmount"
        }
      }
    },
    "Construction": {
      "required": [
        "rp",
        "dc",
        "skills"
      ],
      "properties": {
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ConstructionSkill"
          }
        },
        "lumber": {
          "type": "number"
        },
        "luxuries": {
          "type": "number"
        },
        "ore": {
          "type": "number"
        },
        "stone": {
          "type": "number"
        },
        "rp": {
          "type": "number"
        },
        "dc": {
          "type": "number"
        }
      }
    },
    "ConstructionSkill": {
      "type": "object",
      "required": [
        "skill"
      ],
      "properties": {
        "skill": {
          "$ref": "#/$defs/Skill"
        },
        "proficiencyRank": {
          "type": "number"
        }
      }
    },
    "Skill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "SkillBonusRule": {
      "type": "object",
      "required": [
        "value",
        "skill"
      ],
      "properties": {
        "skill": {
          "$ref": "#/$defs/Skill"
        },
        "value": {
          "type": "number"
        },
        "activity": {
          "type": "string"
        }
      }
    },
    "ActivityBonusRule": {
      "type": "object",
      "required": [
        "value",
        "activity"
      ],
      "properties": {
        "value": {
          "type": "number"
        },
        "activity": {
          "type": "string"
        }
      }
    },
    "AvailableItemsRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        },
        "group": {
          "$ref": "#/$defs/ItemGroup"
        },
        "maximumStacks": {
          "type": "number"
        }
      }
    },
    "ItemGroup": {
      "type": "string",
      "enum": [
        "divine",
        "alchemical",
        "primal",
        "occult",
        "arcane",
        "luxury",
        "magical",
        "other"
      ]
    },
    "SettlementEventsRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        }
      }
    },
    "LeadershipActivityRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        }
      }
    },
    "CommodityStorage": {
      "type": "object",
      "properties": {
        "ore": {
          "type": "number"
        },
        "food": {
          "type": "number"
        },
        "lumber": {
          "type": "number"
        },
        "stone": {
          "type": "number"
        },
        "luxuries": {
          "type": "number"
        }
      }
    },
    "ReduceUnrestBy": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "moreThanOncePerTurn": {
          "type": "boolean"
        },
        "note": {
          "type": "string"
        }
      }
    },
    "RuinAmount": {
      "type": "object",
      "required": [
        "value",
        "ruin"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "ruin": {
          "type": "string",
          "enum": [
            "corruption",
            "crime",
            "decay",
            "strife",
            "any"
          ]
        },
        "moreThanOncePerTurn": {
          "type": "boolean"
        }
      }
    },
    "BuildingTrait": {
      "type": "string",
      "enum": [
        "edifice",
        "yard",
        "building",
        "famous",
        "infamous",
        "residential",
        "infrastructure"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Secure Warehouse.json
{
  "name": "Secure Warehouse",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "craft-luxuries"
    }
  ],
  "storage": {
    "luxuries": 1
  },
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 6,
  "construction": {
    "rp": 24,
    "lumber": 6,
    "stone": 6,
    "ore": 4,
    "skills": [
      {
        "skill": "industry",
        "proficiencyRank": 2
      }
    ],
    "dc": 22
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Mansion.json
{
  "name": "Mansion",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "improve-lifestyle"
    }
  ],
  "traits": [
    "building",
    "residential"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 5,
  "upgradeFrom": [
    "Houses"
  ],
  "construction": {
    "rp": 10,
    "lumber": 6,
    "stone": 3,
    "luxuries": 6,
    "skills": [
      {
        "skill": "industry",
        "proficiencyRank": 1
      }
    ],
    "dc": 20
  },
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Illicit Market.json
{
  "name": "Illicit Market",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "clandestine-business"
    }
  ],
  "availableItemsRules": [
    {
      "value": 1,
      "maximumStacks": 3
    }
  ],
  "traits": [
    "building",
    "infamous"
  ],
  "gainRuin": {
    "value": "1",
    "ruin": "crime",
    "moreThanOncePerTurn": true
  },
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 6,
  "construction": {
    "rp": 50,
    "lumber": 5,
    "skills": [
      {
        "skill": "intrigue",
        "proficiencyRank": 1
      }
    ],
    "dc": 22
  },
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Tavern, Dive (V&K).json
{
  "name": "Tavern, Dive (V&K)",
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": true,
  "reduceUnrestBy": {
    "value": "1"
  },
  "level": 1,
  "construction": {
    "rp": 12,
    "lumber": 1,
    "skills": [
      {
        "skill": "trade",
        "proficiencyRank": 1
      }
    ],
    "dc": 15
  },
  "skillBonusRules": [
    {
      "value": 1,
      "activity": "clear-hex",
      "skill": "exploration"
    }
  ],
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Paved Streets.json
{
    "name": "Paved Streets",
    "traits": [
        "infrastructure"
    ],
    "lots": 0,
    "affectsDowntime": false,
    "reducesUnrest": false,
    "level": 4,
    "construction": {
        "rp": 12,
        "stone": 6,
        "skills": [
            {
                "skill": "industry",
                "proficiencyRank": 1
            }
        ],
        "dc": 19
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Noble Villa.json
{
  "name": "Noble Villa",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "improve-lifestyle"
    }
  ],
  "skillBonusRules": [
    {
      "value": 1,
      "skill": "politics",
      "activity": "quell-unrest"
    }
  ],
  "traits": [
    "building",
    "residential"
  ],
  "affectsDowntime": false,
  "reducesUnrest": true,
  "reduceUnrestBy": {
    "value": "2"
  },
  "level": 9,
  "upgradeFrom": [
    "Mansion"
  ],
  "construction": {
    "rp": 24,
    "lumber": 10,
    "stone": 8,
    "luxuries": 6,
    "skills": [
      {
        "skill": "politics",
        "proficiencyRank": 2
      }
    ],
    "dc": 19
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Park.json
{
  "name": "Park",
  "skillBonusRules": [
    {
      "value": 1,
      "skill": "wilderness",
      "activity": "rest-and-relax"
    }
  ],
  "traits": [
    "yard"
  ],
  "affectsDowntime": false,
  "reducesUnrest": true,
  "reduceUnrestBy": {
    "value": "1"
  },
  "level": 3,
  "construction": {
    "rp": 5,
    "skills": [
      {
        "skill": "wilderness"
      }
    ],
    "dc": 18
  },
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Jail.json
{
  "name": "Jail",
  "skillBonusRules": [
    {
      "value": 1,
      "skill": "intrigue",
      "activity": "quell-unrest"
    }
  ],
  "reduceRuinBy": {
    "value": "1",
    "ruin": "crime"
  },
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesRuin": true,
  "level": 2,
  "construction": {
    "rp": 14,
    "lumber": 4,
    "stone": 4,
    "ore": 2,
    "skills": [
      {
        "skill": "defense"
      }
    ],
    "dc": 16
  },
  "lots": 1
}
