=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/structure.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/structure.json",
  "title": "Structure",
  "description": "A list of structures",
  "$ref": "#/$defs/Structure",
  "$defs": {
    "Structure": {
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "lots"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "stacksWith": {
          "type": "string"
        },
        "construction": {
          "$ref": "#/$defs/Construction"
        },
        "notes": {
          "type": "string"
        },
        "preventItemLevelPenalty": {
          "type": "boolean"
        },
        "enableCapitalInvestment": {
          "type": "boolean"
        },
        "skillBonusRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SkillBonusRule"
          }
        },
        "activityBonusRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityBonusRule"
          }
        },
        "availableItemsRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AvailableItemsRule"
          }
        },
        "settlementEventRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SettlementEventsRule"
          }
        },
        "leadershipActivityRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/LeadershipActivityRule"
          }
        },
        "storage": {
          "$ref": "#/$defs/CommodityStorage"
        },
        "increaseLeadershipActivities": {
          "type": "boolean"
        },
        "isBridge": {
          "type": "boolean"
        },
        "consumptionReduction": {
          "type": "number"
        },
        "unlockActivities": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "traits": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/BuildingTrait"
          }
        },
        "lots": {
          "type": "number"
        },
        "affectsEvents": {
          "type": "boolean"
        },
        "affectsDowntime": {
          "type": "boolean"
        },
        "reducesUnrest": {
          "type": "boolean"
        },
        "reducesRuin": {
          "type": "boolean"
        },
        "level": {
          "type": "number"
        },
        "upgradeFrom": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "reduceUnrestBy": {
          "$ref": "#/$defs/ReduceUnrestBy"
        },
        "reduceRuinBy": {
          "$ref": "#/$defs/RuinAmount"
        },
        "gainRuin": {
          "$ref": "#/$defs/RuinAmount"
        }
      }
    },
    "Construction": {
      "required": [
        "rp",
        "dc",
        "skills"
      ],
      "properties": {
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ConstructionSkill"
          }
        },
        "lumber": {
          "type": "number"
        },
        "luxuries": {
          "type": "number"
        },
        "ore": {
          "type": "number"
        },
        "stone": {
          "type": "number"
        },
        "rp": {
          "type": "number"
        },
        "dc": {
          "type": "number"
        }
      }
    },
    "ConstructionSkill": {
      "type": "object",
      "required": [
        "skill"
      ],
      "properties": {
        "skill": {
          "$ref": "#/$defs/Skill"
        },
        "proficiencyRank": {
          "type": "number"
        }
      }
    },
    "Skill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "SkillBonusRule": {
      "type": "object",
      "required": [
        "value",
        "skill"
      ],
      "properties": {
        "skill": {
          "$ref": "#/$defs/Skill"
        },
        "value": {
          "type": "number"
        },
        "activity": {
          "type": "string"
        }
      }
    },
    "ActivityBonusRule": {
      "type": "object",
      "required": [
        "value",
        "activity"
      ],
      "properties": {
        "value": {
          "type": "number"
        },
        "activity": {
          "type": "string"
        }
      }
    },
    "AvailableItemsRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        },
        "group": {
          "$ref": "#/$defs/ItemGroup"
        },
        "maximumStacks": {
          "type": "number"
        }
      }
    },
    "ItemGroup": {
      "type": "string",
      "enum": [
        "divine",
        "alchemical",
        "primal",
        "occult",
        "arcane",
        "luxury",
        "magical",
        "other"
      ]
    },
    "SettlementEventsRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        }
      }
    },
    "LeadershipActivityRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        }
      }
    },
    "CommodityStorage": {
      "type": "object",
      "properties": {
        "ore": {
          "type": "number"
        },
        "food": {
          "type": "number"
        },
        "lumber": {
          "type": "number"
        },
        "stone": {
          "type": "number"
        },
        "luxuries": {
          "type": "number"
        }
      }
    },
    "ReduceUnrestBy": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "moreThanOncePerTurn": {
          "type": "boolean"
        },
        "note": {
          "type": "string"
        }
      }
    },
    "RuinAmount": {
      "type": "object",
      "required": [
        "value",
        "ruin"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "ruin": {
          "type": "string",
          "enum": [
            "corruption",
            "crime",
            "decay",
            "strife",
            "any"
          ]
        },
        "moreThanOncePerTurn": {
          "type": "boolean"
        }
      }
    },
    "BuildingTrait": {
      "type": "string",
      "enum": [
        "edifice",
        "yard",
        "building",
        "famous",
        "infamous",
        "residential",
        "infrastructure"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Tannery.json
{
  "name": "Tannery",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "trade-commodities"
    }
  ],
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 3,
  "construction": {
    "rp": 6,
    "lumber": 2,
    "skills": [
      {
        "skill": "industry",
        "proficiencyRank": 1
      }
    ],
    "dc": 18
  },
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Waterfront.json
{
    "name": "Waterfront",
    "activityBonusRules": [
        {
            "value": 1,
            "activity": "go-fishing"
        },
        {
            "value": 1,
            "activity": "establish-trade-agreement"
        }
    ],
    "availableItemsRules": [
        {
            "value": 1,
            "maximumStacks": 1,
            "alwaysStacks": true
        }
    ],
    "traits": [
        "yard"
    ],
    "affectsDowntime": false,
    "reducesUnrest": false,
    "level": 8,
    "upgradeFrom": [
        "Pier",
        "Pier (V&K)"
    ],
    "construction": {
        "rp": 90,
        "lumber": 10,
        "skills": [
            {
                "skill": "boating",
                "proficiencyRank": 2
            }
        ],
        "dc": 24
    },
    "lots": 4
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Garrison.json
{
  "name": "Garrison",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "outfit-army"
    },
    {
      "value": 1,
      "activity": "train-army"
    }
  ],
  "traits": [
    "building",
    "residential"
  ],
  "affectsDowntime": false,
  "reducesUnrest": true,
  "reduceUnrestBy": {
    "moreThanOncePerTurn": true,
    "value": "1"
  },
  "level": 5,
  "upgradeFrom": [
    "Barracks"
  ],
  "construction": {
    "skills": [
      {
        "skill": "warfare",
        "proficiencyRank": 1
      }
    ],
    "dc": 20,
    "rp": 28,
    "lumber": 6,
    "stone": 3
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Stable.json
{
  "name": "Stable",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "establish-trade-agreement"
    }
  ],
  "traits": [
    "yard"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 3,
  "construction": {
    "rp": 10,
    "lumber": 2,
    "skills": [
      {
        "skill": "wilderness",
        "proficiencyRank": 1
      }
    ],
    "dc": 18
  },
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Foundry.json
{
  "name": "Foundry",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "establish-work-site-mine"
    }
  ],
  "storage": {
    "ore": 1
  },
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 3,
  "construction": {
    "skills": [
      {
        "skill": "industry",
        "proficiencyRank": 1
      }
    ],
    "dc": 18,
    "rp": 16,
    "lumber": 5,
    "stone": 3,
    "ore": 2
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Keep.json
{
  "name": "Keep",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "deploy-army"
    },
    {
      "value": 1,
      "activity": "garrison-army"
    },
    {
      "value": 1,
      "activity": "train-army"
    }
  ],
  "traits": [
    "building",
    "edifice"
  ],
  "affectsDowntime": false,
  "reducesUnrest": true,
  "reduceUnrestBy": {
    "value": "1"
  },
  "level": 3,
  "construction": {
    "rp": 32,
    "lumber": 8,
    "stone": 8,
    "skills": [
      {
        "skill": "defense",
        "proficiencyRank": 1
      }
    ],
    "dc": 18
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Construction Yard.json
{
  "name": "Construction Yard",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "build-structure"
    },
    {
      "value": 1,
      "activity": "repair-reputation-decay"
    }
  ],
  "traits": [
    "yard"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 10,
  "construction": {
    "skills": [
      {
        "skill": "engineering"
      }
    ],
    "dc": 27,
    "rp": 40,
    "lumber": 10,
    "stone": 10
  },
  "lots": 4
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Bridge.json
{
    "name": "Bridge",
    "isBridge": true,
    "traits": [
        "infrastructure"
    ],
    "lots": 0,
    "affectsDowntime": false,
    "reducesUnrest": false,
    "level": 2,
    "construction": {
        "skills": [
            {
                "skill": "engineering"
            }
        ],
        "dc": 16,
        "rp": 6,
        "lumber": 1
    }
}
