=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/structure.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/structure.json",
  "title": "Structure",
  "description": "A list of structures",
  "$ref": "#/$defs/Structure",
  "$defs": {
    "Structure": {
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "lots"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "stacksWith": {
          "type": "string"
        },
        "construction": {
          "$ref": "#/$defs/Construction"
        },
        "notes": {
          "type": "string"
        },
        "preventItemLevelPenalty": {
          "type": "boolean"
        },
        "enableCapitalInvestment": {
          "type": "boolean"
        },
        "skillBonusRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SkillBonusRule"
          }
        },
        "activityBonusRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityBonusRule"
          }
        },
        "availableItemsRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AvailableItemsRule"
          }
        },
        "settlementEventRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SettlementEventsRule"
          }
        },
        "leadershipActivityRules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/LeadershipActivityRule"
          }
        },
        "storage": {
          "$ref": "#/$defs/CommodityStorage"
        },
        "increaseLeadershipActivities": {
          "type": "boolean"
        },
        "isBridge": {
          "type": "boolean"
        },
        "consumptionReduction": {
          "type": "number"
        },
        "unlockActivities": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "traits": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/BuildingTrait"
          }
        },
        "lots": {
          "type": "number"
        },
        "affectsEvents": {
          "type": "boolean"
        },
        "affectsDowntime": {
          "type": "boolean"
        },
        "reducesUnrest": {
          "type": "boolean"
        },
        "reducesRuin": {
          "type": "boolean"
        },
        "level": {
          "type": "number"
        },
        "upgradeFrom": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "reduceUnrestBy": {
          "$ref": "#/$defs/ReduceUnrestBy"
        },
        "reduceRuinBy": {
          "$ref": "#/$defs/RuinAmount"
        },
        "gainRuin": {
          "$ref": "#/$defs/RuinAmount"
        }
      }
    },
    "Construction": {
      "required": [
        "rp",
        "dc",
        "skills"
      ],
      "properties": {
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ConstructionSkill"
          }
        },
        "lumber": {
          "type": "number"
        },
        "luxuries": {
          "type": "number"
        },
        "ore": {
          "type": "number"
        },
        "stone": {
          "type": "number"
        },
        "rp": {
          "type": "number"
        },
        "dc": {
          "type": "number"
        }
      }
    },
    "ConstructionSkill": {
      "type": "object",
      "required": [
        "skill"
      ],
      "properties": {
        "skill": {
          "$ref": "#/$defs/Skill"
        },
        "proficiencyRank": {
          "type": "number"
        }
      }
    },
    "Skill": {
      "type": "string",
      "enum": [
        "agriculture",
        "arts",
        "boating",
        "defense",
        "engineering",
        "exploration",
        "folklore",
        "industry",
        "intrigue",
        "magic",
        "politics",
        "scholarship",
        "statecraft",
        "trade",
        "warfare",
        "wilderness"
      ]
    },
    "SkillBonusRule": {
      "type": "object",
      "required": [
        "value",
        "skill"
      ],
      "properties": {
        "skill": {
          "$ref": "#/$defs/Skill"
        },
        "value": {
          "type": "number"
        },
        "activity": {
          "type": "string"
        }
      }
    },
    "ActivityBonusRule": {
      "type": "object",
      "required": [
        "value",
        "activity"
      ],
      "properties": {
        "value": {
          "type": "number"
        },
        "activity": {
          "type": "string"
        }
      }
    },
    "AvailableItemsRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        },
        "group": {
          "$ref": "#/$defs/ItemGroup"
        },
        "maximumStacks": {
          "type": "number"
        }
      }
    },
    "ItemGroup": {
      "type": "string",
      "enum": [
        "divine",
        "alchemical",
        "primal",
        "occult",
        "arcane",
        "luxury",
        "magical",
        "other"
      ]
    },
    "SettlementEventsRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        }
      }
    },
    "LeadershipActivityRule": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "number"
        }
      }
    },
    "CommodityStorage": {
      "type": "object",
      "properties": {
        "ore": {
          "type": "number"
        },
        "food": {
          "type": "number"
        },
        "lumber": {
          "type": "number"
        },
        "stone": {
          "type": "number"
        },
        "luxuries": {
          "type": "number"
        }
      }
    },
    "ReduceUnrestBy": {
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "moreThanOncePerTurn": {
          "type": "boolean"
        },
        "note": {
          "type": "string"
        }
      }
    },
    "RuinAmount": {
      "type": "object",
      "required": [
        "value",
        "ruin"
      ],
      "properties": {
        "value": {
          "type": "string"
        },
        "ruin": {
          "type": "string",
          "enum": [
            "corruption",
            "crime",
            "decay",
            "strife",
            "any"
          ]
        },
        "moreThanOncePerTurn": {
          "type": "boolean"
        }
      }
    },
    "BuildingTrait": {
      "type": "string",
      "enum": [
        "edifice",
        "yard",
        "building",
        "famous",
        "infamous",
        "residential",
        "infrastructure"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Stonemason.json
{
  "name": "Stonemason",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "establish-work-site-quarry"
    }
  ],
  "storage": {
    "stone": 1
  },
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 3,
  "construction": {
    "rp": 16,
    "lumber": 2,
    "skills": [
      {
        "skill": "industry",
        "proficiencyRank": 1
      }
    ],
    "dc": 18
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Military Academy.json
{
  "name": "Military Academy",
  "activityBonusRules": [
    {
      "value": 2,
      "activity": "train-army"
    }
  ],
  "skillBonusRules": [
    {
      "value": 2,
      "skill": "warfare",
      "activity": "pledge-of-fealty"
    }
  ],
  "traits": [
    "building",
    "edifice"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 12,
  "upgradeFrom": [
    "Academy"
  ],
  "construction": {
    "rp": 36,
    "lumber": 12,
    "stone": 10,
    "ore": 6,
    "skills": [
      {
        "skill": "warfare",
        "proficiencyRank": 2
      }
    ],
    "dc": 30
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Granary.json
{
  "name": "Granary",
  "storage": {
    "food": 1
  },
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 1,
  "construction": {
    "rp": 12,
    "lumber": 2,
    "skills": [
      {
        "skill": "agriculture"
      }
    ],
    "dc": 15
  },
  "lots": 1
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Wall, Stone.json
{
    "name": "Wall, Stone",
    "traits": [
        "infrastructure"
    ],
    "lots": 0,
    "affectsDowntime": false,
    "reducesUnrest": true,
    "reduceUnrestBy": {
        "value": "1",
        "moreThanOncePerTurn": true,
        "note": "as long as it's the first wall in a settlement"
    },
    "level": 5,
    "upgradeFrom": [
        "Wall, Wooden"
    ],
    "construction": {
        "rp": 4,
        "stone": 8,
        "skills": [
            {
                "skill": "defense",
                "proficiencyRank": 1
            }
        ],
        "dc": 20
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Stockyard.json
{
  "name": "Stockyard",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "gather-livestock"
    }
  ],
  "consumptionReduction": 1,
  "traits": [
    "yard"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 3,
  "construction": {
    "rp": 20,
    "lumber": 4,
    "skills": [
      {
        "skill": "industry"
      }
    ],
    "dc": 18
  },
  "lots": 4
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Magical Streetlamps.json
{
    "name": "Magical Streetlamps",
    "traits": [
        "infrastructure"
    ],
    "lots": 0,
    "affectsDowntime": false,
    "reducesRuin": true,
    "reduceRuinBy": {
        "value": "1",
        "ruin": "crime"
    },
    "level": 5,
    "construction": {
        "rp": 20,
        "skills": [
            {
                "skill": "magic",
                "proficiencyRank": 2
            }
        ],
        "dc": 20
    }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Embassy.json
{
  "name": "Embassy",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "send-diplomatic-envoy"
    },
    {
      "value": 1,
      "activity": "request-foreign-aid"
    }
  ],
  "traits": [
    "building"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 8,
  "construction": {
    "skills": [
      {
        "skill": "politics"
      }
    ],
    "dc": 24,
    "rp": 26,
    "lumber": 10,
    "stone": 4,
    "luxuries": 6
  },
  "lots": 2
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/structures/Construction Yard (V&K).json
{
  "name": "Construction Yard (V&K)",
  "activityBonusRules": [
    {
      "value": 1,
      "activity": "build-structure"
    },
    {
      "value": 1,
      "activity": "repair-reputation-decay"
    },
    {
      "value": 1,
      "activity": "build-roads"
    },
    {
      "value": 1,
      "activity": "irrigation"
    }
  ],
  "traits": [
    "yard"
  ],
  "affectsDowntime": false,
  "reducesUnrest": false,
  "level": 10,
  "construction": {
    "skills": [
      {
        "skill": "engineering"
      }
    ],
    "dc": 27,
    "rp": 40,
    "lumber": 10,
    "stone": 10
  },
  "lots": 4
}
